default_config:

automation: !include automations.yaml
binary_sensor: !include binary_sensors.yaml
group: !include groups.yaml
light: !include lights.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
timer: !include timers.yaml

frontend:
  themes: !include_dir_merge_named themes

logger:
  default: warning

recorder:
  purge_keep_days: 30

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

influxdb:
  database: !secret influxdb-database
  username: !secret influxdb-user
  password: !secret influxdb-password
  max_retries: 3
  default_measurement: state

tts:
  - platform: google_translate
