# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
timer: !include timers.yaml

homeassistant:
  customize: !include customize.yaml

  packages:
    homematic: !include packages/homematic.yaml

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

telegram_bot:
  - platform: polling
    api_key: !secret telegram-api-key
    allowed_chat_ids: !secret telegram-allowed-chat-ids

notify:
  - name: telegram_admin
    platform: telegram
    chat_id: !secret telegram-chat-id-admin

influxdb:
  database: !secret influxdb-database
  username: !secret influxdb-user
  password: !secret influxdb-password
  max_retries: 3
  default_measurement: state
