default_config:

automation: !include automations.yaml
binary_sensor: !include binary_sensors.yaml
group: !include groups.yaml
light: !include lights.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
timer: !include timers.yaml

python_script:

frontend:
  themes: !include_dir_merge_named themes

logger:
  default: warning

recorder:
  db_url: !secret mariadb-url
  purge_keep_days: 7

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages

influxdb:
  database: !secret influxdb-database
  username: !secret influxdb-user
  password: !secret influxdb-password
  max_retries: 3
  default_measurement: state

tts:
  - platform: google_cloud
    key_file: apikey-google-cloud.json
    voice: de-DE-Wavenet-F

http:
  use_x_forwarded_for: true
  trusted_proxies: # Docker containers
    - 172.30.33.0/24
