default_config:

automation: !include automations.yaml
script: !include scripts.yaml

python_script:

frontend:
  themes: !include_dir_merge_named themes

logger:
  default: warning

recorder:
  db_url: !secret mariadb-url
  purge_keep_days: 7
  exclude:
    entities:
      - sensor.average_power_zuhause
      - sensor.last_meter_consumption_zuhause
      - sensor.power_zuhause

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages

influxdb: !include influxdb.yaml

tts:
  - platform: google_cloud
    key_file: apikey-google-cloud.json
    voice: de-DE-Wavenet-F

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24 # Docker containers

  ip_ban_enabled: true
  login_attempts_threshold: 5
