- platform: dwd_weather_warnings
  region_name: Stadt Frankfurt am Main
  name: Frankfurt am Main

- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "date_time_utc"
    - "date_time_iso"
    - "time_date"
    - "time_utc"
    - "beat"
