substitutions:
  name: esp32-bluetooth-proxy-c912c8
  friendly_name: Bluetooth Proxy Garage
  api_encryption_key: "GaTKf6yMT+sKwgpW/eLDDDM0iN1AxYCdG+V7+Eu7q9M="

packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic.yaml@main
  
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  comment: "Bluetooth Proxy on generic ESP32 board with Wi-Fi and Bluetooth"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

api:
  encryption:
    key: ${api_encryption_key}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true