substitutions:
  name: garagentor
  friendly_name: Garagentor
  api_encryption_key: "AnPvytk6Gw6QOHEXDWkNYJjVLDo/ablP/ZlFg1x+FLM="

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  comment: "Shelly 1 relais controlling the garage door"

esp8266:
  board: esp01_1m

logger:

api:
  encryption:
    key: ${api_encryption_key}

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "${name}-AP"
    password: !secret wifi_ap_password

captive_portal:

time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  - platform: gpio
    name: "State"
    id: state
    device_class: garage_door
    pin:
      number: GPIO5
      inverted: true

switch:
  - platform: gpio
    id: relay
    pin: GPIO4
    name: "Switch"
    
button:
  - platform: template
    name: "Trigger"
    on_press:
      then:
        - switch.turn_on: relay
        - delay: 200ms
        - switch.turn_off: relay
  - platform: restart
    name: "Restart"

sensor:
  - platform: uptime
    name: "Uptime"

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s