substitutions:
  name: "steckdose-8343af"
  friendly_name: "Steckdose 8343af"
  api_encryption_key: "oFSAMW/fn2/Sudlx7r6u/D+JBDdmmDvcGFYH+miD6QQ="

  # Higher value gives lower watt readout
  current_res: "0.00280"
  # Lower value gives lower voltage readout
  voltage_div: "775"

<<: !include .steckdose.yaml