substitutions:
  name: "steckdose-klimaanlage"
  friendly_name: "Steckdose Klimaanlage"
  api_encryption_key: "grSl9VtX1L/QMY+dyIWjhWoinijO4rP6TxsBGxtg3e0="

  # Higher value gives lower watt readout
  current_res: "0.00280"
  # Lower value gives lower voltage readout
  voltage_div: "775"

<<: !include .steckdose.yaml  