substitutions:
  name: "steckdose-keller"
  friendly_name: "Steckdose Keller"
  api_encryption_key: "WWuizIU4nupjNesYhepznKlGn1QzxyG8sxN0PidkRFM="

  # Higher value gives lower watt readout
  current_res: "0.00280"
  # Lower value gives lower voltage readout
  voltage_div: "775"

<<: !include .steckdose.yaml  