substitutions:
  name: steckdose-arbeitszimmer
  friendly_name: "Steckdose Arbeitszimmer"
  api_encryption_key: "9EcTtUqYul2yQ0UeGds7tmCM9S4IIfmw8Qeb7eVwlaA="

  # Higher value gives lower watt readout
  current_res: "0.00280"
  # Lower value gives lower voltage readout
  voltage_div: "775"

<<: !include .steckdose.yaml