substitutions:
  name: steckdose-wohnzimmer-tv
  friendly_name: "Steckdose Wohnzimmer TV"
  api_encryption_key: "52YnhBAz/e7hJbux0/isU9WjFPoOyUlNxDzaaQwrvRA="

  # Higher value gives lower watt readout
  current_res: "0.00280"
  # Lower value gives lower voltage readout
  voltage_div: "775"

<<: !include .steckdose.yaml  