substitutions:
  name: steckdose-waschmaschine
  friendly_name: "Steckdose Waschmaschine"
  api_encryption_key: "WwPIRFclBnWX24jSpiOmp7+5fmFWViMagkEvdmR8q80="
  
  # Higher value gives lower watt readout
  current_res: "0.00280"
  # Lower value gives lower voltage readout
  voltage_div: "775"

<<: !include .steckdose.yaml  