substitutions:
  name: display-waschraum-lueftung
  friendly_name: Display Waschraum Lüftung

api:
  encryption:
    key: dHjusSzRZTM1iEoJQJ72f4T2IxPPIdV1bHyyO02X5X0=

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

  on_boot:
    then:
      - output.turn_on: epd_power_enable
      - display.page.show: pg_starting

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
  variant: ESP32S3
  cpu_frequency: 80MHz

logger:

output:
  - platform: gpio
    pin: GPIO6 # EPD3V3_EN pin GHF: Required by the ePaper display!!!
    id: epd_power_enable
    inverted: True
    
  - platform: gpio
    pin: 
      number: GPIO17 # BATT_Control pin GHF: Required by the battery to work!!!
      #allow_other_uses: True # GHF: Required here cause it is used in deep sleep as wakeup pin
    id: vbat_power_enable
    
  - platform: gpio
    pin: GPIO3
    id: green_led_pin
    inverted: True

light:
  - platform: binary
    output: green_led_pin
    id: green_led
    name: green_led

spi:
  clk_pin: GPIO12 # SCK
  mosi_pin: GPIO13 # SDO

i2c:
  sda: GPIO47
  scl: GPIO48

display:
  - platform: waveshare_epaper
    model: 1.54inv2 # 200x200 pixels
    cs_pin: GPIO11 # CS (Chip Select)
    dc_pin: GPIO10 # DC (Data/Command)
    busy_pin: GPIO8 # BUSY pin (required to check when the display is ready)
    reset_pin: GPIO9 # RST (Reset)
    update_interval: never
    reset_duration: 2ms
    full_update_every: 1
    rotation: 90
    id: my_display
    pages:
      - id: pg_starting # this page is shown by default initially
        lambda: |-
          it.printf(100, 100, id(font_roboto), TextAlign::CENTER, "Starting");

font:
  - file:
      type: gfonts
      family: Source Code Pro
      weight: 700
    id: font_roboto
    size: 26
  - file: "gfonts://Roboto"
    id: roboto_20
    size: 20