blueprint:
  name: Window open, climate off after a defined time
  description: An automation that turns off a running your climate device for example
    a heater or an air conditioning if a window sensor is open for a specific time.
    It waits until the window is closed again in order to turn the climate entity
    on again.
  domain: automation
  input:
    window_entity:
      name: Window Sensor
      description: The window sensor that controls the climate device.
      selector:
        entity:
          domain: binary_sensor
          device_class: window
    minimum_open_time:
      name: Minimum time the window is open
      description: Time in seconds to wait until the automation is triggered
      default: 300
      selector:
        number:
          min: 0
          max: 900
          unit_of_measurement: seconds
          mode: slider
          step: 15
    climate_target:
      name: Climate Device
      description: The climate device that is controlled by the window sensor.
      selector:
        entity:
          domain: climate
trigger:
- platform: state
  entity_id: !input 'window_entity'
  to: 'on'
  for: !input 'minimum_open_time'
condition:
- condition: not
  conditions:
  - condition: state
    entity_id: !input 'climate_target'
    state: 'off'
action:
- service: climate.turn_off
  entity_id: !input 'climate_target'
- wait_for_trigger:
  - platform: state
    entity_id: !input 'window_entity'
    to: 'off'
  continue_on_timeout: false
- service: climate.turn_on
  entity_id: !input 'climate_target'
