mqtt:
  sensor:
    - name: "CO2"
      object_id: air_monitor_co2
      device_class: carbon_dioxide
      unit_of_measurement: "ppm"
      state_topic: "qingping/582D34700B3E/up"
      value_template: >-
        {{ value_json.sensorData.0.co2.value
          if value_json else this.state }}
      availability:
        - topic: "qingping/582D34700B3E/up"
          payload_available: "true"
          payload_not_available: "false"
          value_template: >-
            {{ "true" if value_json else "false" }}
      device:
        identifiers: ["582D34700B3E"]
        name: "Air monitor"
        model: "CGS1"
        manufacturer: "qingping"
      unique_id: f0864ae1d3e66cdb5a29c894dd6a192f8ba528ec
    - name: "PM2.5"
      object_id: air_monitor_pm25
      device_class: pm25
      state_topic: "qingping/582D34700B3E/up"
      value_template: >-
        {{ value_json.sensorData.0.pm25.value 
          if value_json else this.state }}
      unit_of_measurement: "µg/m³"
      availability:
        - topic: "qingping/582D34700B3E/up"
          payload_available: "true"
          payload_not_available: "false"
          value_template: >-
            {{ "true" if value_json else "false" }}
      device:
        identifiers: ["582D34700B3E"]
        name: "Air monitor"
        model: "CGS1"
        manufacturer: "qingping"
      unique_id: 0c4f328dd042cdfc17f01ec2f880e7dd5317750b
    - name: "PM10"
      object_id: air_monitor_pm10
      device_class: pm10
      unit_of_measurement: "µg/m³"
      state_topic: "qingping/582D34700B3E/up"
      value_template: >-
        {{ value_json.sensorData.0.pm10.value 
          if value_json else this.state }}
      availability:
        - topic: "qingping/582D34700B3E/up"
          payload_available: "true"
          payload_not_available: "false"
          value_template: >-
            {{ "true" if value_json else "false" }}
      device:
        identifiers: ["582D34700B3E"]
        name: "Air monitor"
        model: "CGS1"
        manufacturer: "qingping"
      unique_id: 0e330464965310305e8df5187ba00e5a6b515471
    - name: "TVOC"
      object_id: air_monitor_tvoc
      device_class: volatile_organic_compounds
      unit_of_measurement: "µg/m³"
      state_topic: "qingping/582D34700B3E/up"
      value_template: >-
        {{ (value_json.sensorData.0.tvoc.value / 218.77) | round(3) 
          if value_json else this.state }}
      availability:
        - topic: "qingping/582D34700B3E/up"
          payload_available: "true"
          payload_not_available: "false"
          value_template: >-
            {{ "true" if value_json else "false" }}
      device:
        identifiers: ["582D34700B3E"]
        name: "Air monitor"
        model: "CGS1"
        manufacturer: "qingping"
      unique_id: 145ba4f594273ed8cfcf44f8df1983e3a229b0d1
    - name: "Luftfeuchtigkeit"
      object_id: air_monitor_humidity
      device_class: humidity
      state_topic: "qingping/582D34700B3E/up"
      value_template: >-
        {{ value_json.sensorData.0.humidity.value|round(2)
          if value_json else this.state }}
      unit_of_measurement: "%"
      availability:
        - topic: "qingping/582D34700B3E/up"
          payload_available: "true"
          payload_not_available: "false"
          value_template: >-
            {{ "true" if value_json else "false" }}
      device:
        identifiers: ["582D34700B3E"]
        name: "Air monitor"
        model: "CGS1"
        manufacturer: "qingping"
      unique_id: 5648fe503a9c4c7563643425de97f184a3282a66
    - object_id: air_monitor_temperature
      name: "Temperatur"
      device_class: temperature
      unit_of_measurement: "°C"
      state_topic: "qingping/582D34700B3E/up"
      value_template: >-
        {{ value_json.sensorData.0.temperature.value|round(2)
            if value_json else this.state }}
      availability:
        - topic: "qingping/582D34700B3E/up"
          payload_available: "true"
          payload_not_available: "false"
          value_template: >-
            {{ "true" if value_json else "false" }}
      device:
        identifiers: ["582D34700B3E"]
        name: "Air monitor"
        model: "CGS1"
        manufacturer: "qingping"
      unique_id: eeac725e7c2bc220e8ef3602b7a506a9855a36c6

template:
  - sensor:
      - name: "Air Monitor CO2 Status"
        unique_id: air_monitor_co2_status
        state: >
          {{ {0: "normal", 1: "erhöht", 2: "hoch", 3: "sehr hoch"}[
            [1000, 2000, 3000] | select("<=", states('sensor.air_monitor_co2') | float(0)) | list | length
          ] }}
        availability: >
          {{ not is_state('sensor.air_monitor_tvoc', 'unavailable') }}
        icon: mdi:molecule
      - name: "Air Monitor PM2.5 Status"
        unique_id: air_monitor_pm25_status
        state: >
          {{ {0: "gut", 1: "moderat", 2: "etwas ungesund", 3: "ungesund", 4: "sehr ungesund", 5: "gefährlich"}[
            [12, 35, 55, 150, 250] | select("<=", states('sensor.air_monitor_pm25') | float(0) ) | list | length
          ] }}
        availability: >
          {{ not is_state('sensor.air_monitor_pm25', 'unavailable') }}
        icon: mdi:molecule
      - name: "Air Monitor TVOC Status"
        unique_id: air_monitor_tvoc_status
        state: >
          {{ {0: "ausgezeichnet", 1: "gut", 2: "erhöht", 3: "hoch", 4: "sehr hoch"}[
            [0.3, 1, 3, 9] | select("<=", states('sensor.air_monitor_tvoc') | float(0) ) | list | length
          ] }}
        availability: >
          {{ not is_state('sensor.air_monitor_tvoc', 'unavailable') }}
        icon: mdi:molecule

automation:
  - alias: Activate near-time reporting of Qingping Air Sensor
    triggers:
      - trigger: homeassistant
        event: start
      - trigger: time
        at:
        - "03:00:00"
    actions:
      - action: mqtt.publish
        data:
          topic: qingping/582D34700B3E/down
          payload: >-
            {"type": "12", "up_itvl": "15" ,"duration": "86400"}
    id: a20cb2c8aa6253f8607bc3572ecd25d8a3d279f8
