input_boolean:
  blind_control_active_global:
    name: "Rolladensteuerung: aktiv"
    icon: mdi:window-shutter
  blind_control_active_kueche:
    name: "Rolladensteuerung: aktiv (Küche)"
    icon: mdi:window-shutter
  blind_control_active_wohnzimmer:
    name: "Rolladensteuerung: aktiv (Wohnzimmer)"
    icon: mdi:window-shutter
  blind_control_active_schlafzimmer:
    name: "Rolladensteuerung: aktiv (Schlafzimmer)"
    icon: mdi:window-shutter
  blind_control_active_badezimmer:
    name: "Rolladensteuerung: aktiv (Badezimmer)"
    icon: mdi:window-shutter
  blind_control_active_duschbad:
    name: "Rolladensteuerung: aktiv (Duschbad)"
    icon: mdi:window-shutter
  blind_control_active_nino:
    name: "Rolladensteuerung: aktiv (Nino)"
    icon: mdi:window-shutter
  blind_control_active_noah:
    name: "Rolladensteuerung: aktiv (Noah)"
    icon: mdi:window-shutter
  blind_control_active_arbeitszimmer:
    name: "Rolladensteuerung: aktiv (Arbeitszimmer)"
    icon: mdi:window-shutter
  blind_control_auto_global:
    name: "Rolladensteuerung: Sonnenstandsteuerung automatisch"
    icon: mdi:cog-refresh-outline
  blind_control_auto_kueche:
    name: "Rolladensteuerung: Sonnenstandsteuerung automatisch (Küche)"
    icon: mdi:cog-refresh-outline
  blind_control_auto_wohnzimmer:
    name: "Rolladensteuerung: Sonnenstandsteuerung automatisch (Wohnzimmer)"
    icon: mdi:cog-refresh-outline
  blind_control_auto_schlafzimmer:
    name: "Rolladensteuerung: Sonnenstandsteuerung automatisch (Schlafzimmer)"
    icon: mdi:cog-refresh-outline
  blind_control_auto_badezimmer:
    name: "Rolladensteuerung: Sonnenstandsteuerung automatisch (Badezimmer)"
    icon: mdi:cog-refresh-outline
  blind_control_auto_duschbad:
    name: "Rolladensteuerung: Sonnenstandsteuerung automatisch (Duschbad)"
    icon: mdi:cog-refresh-outline
  blind_control_auto_nino:
    name: "Rolladensteuerung: Sonnenstandsteuerung automatisch (Nino)"
    icon: mdi:cog-refresh-outline
  blind_control_auto_noah:
    name: "Rolladensteuerung: Sonnenstandsteuerung automatisch (Noah)"
    icon: mdi:cog-refresh-outline
  blind_control_auto_arbeitszimmer:
    name: "Rolladensteuerung: Sonnenstandsteuerung automatisch (Arbeitszimmer)"
  blind_control_on_global:
    name: "Rolladensteuerung: an"
    icon: mdi:car-clutch
  blind_control_specific_global:
    name: "Rolladensteuerung: gesondert gesteuerte Räume zurücksetzen"
    icon: mdi:lock-alert-outline
  blind_control_specific_badezimmer:
    name: "Rolladensteuerung: gesondert steuern (Badezimmer)"
    icon: mdi:lock-open-outline
  blind_control_specific_duschbad:
    name: "Rolladensteuerung: gesondert steuern (Duschbad)"
    icon: mdi:lock-open-outline
  blind_control_specific_nino:
    name: "Rolladensteuerung: gesondert steuern (Nino)"
    icon: mdi:lock-open-outline
  blind_control_specific_noah:
    name: "Rolladensteuerung: gesondert steuern (Noah)"
    icon: mdi:lock-open-outline
  blind_control_specific_arbeitszimmer:
    name: "Rolladensteuerung: gesondert steuern (Arbeitszimmer)"
    icon: mdi:lock-open-outline
  blind_control_specific_kueche:
    name: "Rolladensteuerung: gesondert steuern (Küche)"
    icon: mdi:lock-open-outline
  blind_control_specific_wohnzimmer:
    name: "Rolladensteuerung: gesondert steuern (Wohnzimmer)"
    icon: mdi:lock-open-outline
  blind_control_specific_schlafzimmer:
    name: "Rolladensteuerung: gesondert steuern (Schlafzimmer)"
    icon: mdi:lock-open-outline
  blind_control_raining:
    name: "Rolladensteuerung: Regen"
    icon: mdi:weather-pouring

input_select:
  blind_control_mode_global:
    name: "Rolladensteuerung: Sonnenstandsteuerung"
    icon: mdi:weather-partly-snowy
    options:
      - "0 (aus)"
      - "1 (Winter)"
      - "2 (Sommer)"
  blind_control_mode_kueche:
    name: "Rolladensteuerung: Sonnenstandsteuerung (Küche)"
    icon: mdi:weather-partly-snowy
    options:
      - "0 (aus)"
      - "1 (Winter)"
      - "2 (Sommer)"
  blind_control_mode_wohnzimmer:
    name: "Rolladensteuerung: Sonnenstandsteuerung (Wohnzimmer)"
    icon: mdi:weather-partly-snowy
    options:
      - "0 (aus)"
      - "1 (Winter)"
      - "2 (Sommer)"
  blind_control_mode_schlafzimmer:
    name: "Rolladensteuerung: Sonnenstandsteuerung (Schlafzimmer)"
    icon: mdi:weather-partly-snowy
    options:
      - "0 (aus)"
      - "1 (Winter)"
      - "2 (Sommer)"
  blind_control_mode_badezimmer:
    name: "Rolladensteuerung: Sonnenstandsteuerung (Badezimmer)"
    icon: mdi:weather-partly-snowy
    options:
      - "0 (aus)"
      - "1 (Winter)"
      - "2 (Sommer)"
  blind_control_mode_duschbad:
    name: "Rolladensteuerung: Sonnenstandsteuerung (Duschbad)"
    icon: mdi:weather-partly-snowy
    options:
      - "0 (aus)"
      - "1 (Winter)"
      - "2 (Sommer)"
  blind_control_mode_nino:
    name: "Rolladensteuerung: Sonnenstandsteuerung (Nino)"
    icon: mdi:weather-partly-snowy
    options:
      - "0 (aus)"
      - "1 (Winter)"
      - "2 (Sommer)"
  blind_control_mode_noah:
    name: "Rolladensteuerung: Sonnenstandsteuerung (Noah)"
    icon: mdi:weather-partly-snowy
    options:
      - "0 (aus)"
      - "1 (Winter)"
      - "2 (Sommer)"
  blind_control_mode_arbeitszimmer:
    name: "Rolladensteuerung: Sonnenstandsteuerung (Arbeitszimmer)"
    icon: mdi:weather-partly-snowy
    options:
      - "0 (aus)"
      - "1 (Winter)"
      - "2 (Sommer)"

input_number:
  blind_control_position_global:
    name: "Rolladensteuerung: alle … % öffnen (–10 = aus)"
    icon: mdi:arrow-split-horizontal
    min: -20
    max: 100
    step: 10
  blind_control_position_kueche:
    name: "Rolladensteuerung: alle … % öffnen (–10 = aus) (Küche)"
    icon: mdi:arrow-split-horizontal
    min: -20
    max: 100
    step: 10
  blind_control_position_wohnzimmer:
    name: "Rolladensteuerung: alle … % öffnen (–10 = aus) (Wohnzimmer)"
    icon: mdi:arrow-split-horizontal
    min: -20
    max: 100
    step: 10
  blind_control_position_schlafzimmer:
    name: "Rolladensteuerung: alle … % öffnen (–10 = aus) (Schlafzimmer)"
    icon: mdi:arrow-split-horizontal
    min: -20
    max: 100
    step: 10
  blind_control_position_badezimmer:
    name: "Rolladensteuerung: alle … % öffnen (–10 = aus) (Badezimmer)"
    icon: mdi:arrow-split-horizontal
    min: -20
    max: 100
    step: 10
  blind_control_position_duschbad:
    name: "Rolladensteuerung: alle … % öffnen (–10 = aus) (Duschbad)"
    icon: mdi:arrow-split-horizontal
    min: -20
    max: 100
    step: 10
  blind_control_position_nino:
    name: "Rolladensteuerung: alle … % öffnen (–10 = aus) (Nino)"
    icon: mdi:arrow-split-horizontal
    min: -20
    max: 100
    step: 10
  blind_control_position_noah:
    name: "Rolladensteuerung: alle … % öffnen (–10 = aus) (Noah)"
    icon: mdi:arrow-split-horizontal
    min: -20
    max: 100
    step: 10
  blind_control_position_arbeitszimmer:
    name: "Rolladensteuerung: alle … % öffnen (–10 = aus) (Arbeitszimmer)"
    icon: mdi:arrow-split-horizontal
    min: -20
    max: 100
    step: 10

input_datetime:
  blind_control_from_earliest_workday_global:
    name: "Rolladensteuerung: an Werktagen frühestens"
    icon: mdi:weather-sunset-up
    has_time: true
  blind_control_until_latest_workday_global:
    name: "Rolladensteuerung: vor Werktagen spätestens"
    icon: mdi:weather-sunset-down
    has_time: true
  blind_control_from_earliest_holiday_global:
    name: "Rolladensteuerung: an Feiertagen frühestens"
    icon: mdi:weather-sunset-up
    has_time: true
  blind_control_until_latest_holiday_global:
    name: "Rolladensteuerung: vor Feiertagen spätestens"
    icon: mdi:weather-sunset-down
    has_time: true
  blind_control_from_earliest_workday_badezimmer:
    name: "Rolladensteuerung: an Werktagen frühestens (Badezimmer)"
    icon: mdi:weather-sunset-up
    has_time: true
  blind_control_until_latest_workday_badezimmer:
    name: "Rolladensteuerung: vor Werktagen spätestens (Badezimmer)"
    icon: mdi:weather-sunset-down
    has_time: true
  blind_control_from_earliest_holiday_badezimmer:
    name: "Rolladensteuerung: an Feiertagen frühestens (Badezimmer)"
    icon: mdi:weather-sunset-up
    has_time: true
  blind_control_until_latest_holiday_badezimmer:
    name: "Rolladensteuerung: vor Feiertagen spätestens (Badezimmer)"
    icon: mdi:weather-sunset-down
    has_time: true
  blind_control_from_earliest_workday_duschbad:
    name: "Rolladensteuerung: an Werktagen frühestens (Duschbad)"
    icon: mdi:weather-sunset-up
    has_time: true
  blind_control_until_latest_workday_duschbad:
    name: "Rolladensteuerung: vor Werktagen spätestens (Duschbad)"
    icon: mdi:weather-sunset-down
    has_time: true
  blind_control_from_earliest_holiday_duschbad:
    name: "Rolladensteuerung: an Feiertagen frühestens (Duschbad)"
    icon: mdi:weather-sunset-up
    has_time: true
  blind_control_until_latest_holiday_duschbad:
    name: "Rolladensteuerung: vor Feiertagen spätestens (Duschbad)"
    icon: mdi:weather-sunset-down
    has_time: true
  blind_control_from_earliest_workday_nino:
    name: "Rolladensteuerung: an Werktagen frühestens (Nino)"
    icon: mdi:weather-sunset-up
    has_time: true
  blind_control_until_latest_workday_nino:
    name: "Rolladensteuerung: vor Werktagen spätestens (Nino)"
    icon: mdi:weather-sunset-down
    has_time: true
  blind_control_from_earliest_holiday_nino:
    name: "Rolladensteuerung: an Feiertagen frühestens (Nino)"
    icon: mdi:weather-sunset-up
    has_time: true
  blind_control_until_latest_holiday_nino:
    name: "Rolladensteuerung: vor Feiertagen spätestens (Nino)"
    icon: mdi:weather-sunset-down
    has_time: true
  blind_control_from_earliest_workday_noah:
    name: "Rolladensteuerung: an Werktagen frühestens (Noah)"
    icon: mdi:weather-sunset-up
    has_time: true
  blind_control_until_latest_workday_noah:
    name: "Rolladensteuerung: vor Werktagen spätestens (Noah)"
    icon: mdi:weather-sunset-down
    has_time: true
  blind_control_from_earliest_holiday_noah:
    name: "Rolladensteuerung: an Feiertagen frühestens (Noah)"
    icon: mdi:weather-sunset-up
    has_time: true
  blind_control_until_latest_holiday_noah:
    name: "Rolladensteuerung: vor Feiertagen spätestens (Noah)"
    icon: mdi:weather-sunset-down
    has_time: true
  blind_control_from_earliest_workday_arbeitszimmer:
    name: "Rolladensteuerung: an Werktagen frühestens (Arbeitszimmer)"
    icon: mdi:weather-sunset-up
    has_time: true
  blind_control_until_latest_workday_arbeitszimmer:
    name: "Rolladensteuerung: vor Werktagen spätestens (Arbeitszimmer)"
    icon: mdi:weather-sunset-down
    has_time: true
  blind_control_from_earliest_holiday_arbeitszimmer:
    name: "Rolladensteuerung: an Feiertagen frühestens (Arbeitszimmer)"
    icon: mdi:weather-sunset-up
    has_time: true
  blind_control_until_latest_holiday_arbeitszimmer:
    name: "Rolladensteuerung: vor Feiertagen spätestens (Arbeitszimmer)"
    icon: mdi:weather-sunset-down
    has_time: true
  blind_control_from_earliest_workday_kueche:
    name: "Rolladensteuerung: an Werktagen frühestens (Küche)"
    icon: mdi:weather-sunset-up
    has_time: true
  blind_control_until_latest_workday_kueche:
    name: "Rolladensteuerung: vor Werktagen spätestens (Küche)"
    icon: mdi:weather-sunset-down
    has_time: true
  blind_control_from_earliest_holiday_kueche:
    name: "Rolladensteuerung: an Feiertagen frühestens (Küche)"
    icon: mdi:weather-sunset-up
    has_time: true
  blind_control_until_latest_holiday_kueche:
    name: "Rolladensteuerung: vor Feiertagen spätestens (Küche)"
    icon: mdi:weather-sunset-down
    has_time: true
  blind_control_from_earliest_workday_wohnzimmer:
    name: "Rolladensteuerung: an Werktagen frühestens (Wohnzimmer)"
    icon: mdi:weather-sunset-up
    has_time: true
  blind_control_until_latest_workday_wohnzimmer:
    name: "Rolladensteuerung: vor Werktagen spätestens (Wohnzimmer)"
    icon: mdi:weather-sunset-down
    has_time: true
  blind_control_from_earliest_holiday_wohnzimmer:
    name: "Rolladensteuerung: an Feiertagen frühestens (Wohnzimmer)"
    icon: mdi:weather-sunset-up
    has_time: true
  blind_control_until_latest_holiday_wohnzimmer:
    name: "Rolladensteuerung: vor Feiertagen spätestens (Wohnzimmer)"
    icon: mdi:weather-sunset-down
    has_time: true
  blind_control_from_earliest_workday_schlafzimmer:
    name: "Rolladensteuerung: an Werktagen frühestens (Schlafzimmer)"
    icon: mdi:weather-sunset-up
    has_time: true
  blind_control_until_latest_workday_schlafzimmer:
    name: "Rolladensteuerung: vor Werktagen spätestens (Schlafzimmer)"
    icon: mdi:weather-sunset-down
    has_time: true
  blind_control_from_earliest_holiday_schlafzimmer:
    name: "Rolladensteuerung: an Feiertagen frühestens (Schlafzimmer)"
    icon: mdi:weather-sunset-up
    has_time: true
  blind_control_until_latest_holiday_schlafzimmer:
    name: "Rolladensteuerung: vor Feiertagen spätestens (Schlafzimmer)"
    icon: mdi:weather-sunset-down
    has_time: true

template:
  binary_sensor:
    - name: marquee_is_open
      state: >
        {{ states("binary_sensor.strips_mazw_access_control_window_door_is_open") }}
      device_class: opening
      icon: mdi:window-closed
    - name: window_sensor_wohnzimmer_any_window_is_open
      state: >
        {{ is_state("binary_sensor.window_sensor_wohnzimmer_window_is_open", "on") or is_state("binary_sensor.door_sensor_terrasse_access_control_door_is_open", "on") }}
    - name: window_sensor_kueche_any_window_is_open
      state: >
        {{ is_state("binary_sensor.window_sensor_kueche_links_window_is_open", "on") or is_state("binary_sensor.window_sensor_kueche_rechts_window_is_open", "on") }}
    - name: window_sensor_nino_any_window_is_open
      state: >
        {{ is_state("binary_sensor.window_sensor_nino_links_window_is_open", "on") or is_state("binary_sensor.window_sensor_nino_rechts_window_is_open", "on") }}
    - name: window_sensor_noah_any_window_is_open
      state: >
        {{ is_state("binary_sensor.window_sensor_noah_links_window_is_open", "on") or is_state("binary_sensor.window_sensor_noah_rechts_window_is_open", "on") }}

homeassistant:
  customize:
    binary_sensor.marquee_is_open:
      friendly_name: "Markise ist"
    binary_sensor.window_sensor_badezimmer_window_is_open:
      friendly_name: Fenster Badezimmer
      device_class: window
    binary_sensor.window_sensor_arbeitszimmer_window_is_open:
      friendly_name: Fenster Arbeitszimmer
      device_class: window
    binary_sensor.window_sensor_duschbad_window_is_open:
      friendly_name: Fenster Duschbad
      device_class: window
    binary_sensor.window_sensor_schlafzimmer_window_is_open:
      friendly_name: Fenster Schlafzimmer
      device_class: window
    binary_sensor.window_sensor_wohnzimmer_any_window_is_open:
      friendly_name: Fenster Wohnzimmer (mindestens eins offen)
      device_class: window
    binary_sensor.window_sensor_kueche_any_window_is_open:
      friendly_name: Fenster Küche (mindestens eins offen)
      device_class: window
    binary_sensor.window_sensor_nino_any_window_is_open:
      friendly_name: Fenster Nino (mindestens eins offen)
      device_class: window
    binary_sensor.window_sensor_noah_any_window_is_open:
      friendly_name: Fenster Noah (mindestens eins offen)
      device_class: window
    sensor.blind_control_badezimmer:
      friendly_name: "Badezimmer"
      icon: hass:arrow-split-horizontal
    sensor.blind_control_duschbad:
      friendly_name: "Duschbad"
      icon: hass:arrow-split-horizontal
    sensor.blind_control_nino_rechts:
      friendly_name: "Nino (rechts)"
      icon: hass:arrow-split-horizontal
    sensor.blind_control_nino_links:
      friendly_name: "Nino (links)"
      icon: hass:arrow-split-horizontal
    sensor.blind_control_noah_rechts:
      friendly_name: "Noah (rechts)"
      icon: hass:arrow-split-horizontal
    sensor.blind_control_noah_links:
      friendly_name: "Noah (links)"
      icon: hass:arrow-split-horizontal
    sensor.blind_control_arbeitszimmer:
      friendly_name: "Arbeitszimmer"
      icon: hass:arrow-split-horizontal
    sensor.blind_control_kueche_rechts:
      friendly_name: "Küche (rechts)"
      icon: hass:arrow-split-horizontal
    sensor.blind_control_kueche_links:
      friendly_name: "Küche (links)"
      icon: hass:arrow-split-horizontal
    sensor.blind_control_wohnzimmer:
      friendly_name: "Wohnzimmer"
      icon: hass:arrow-split-horizontal
    sensor.blind_control_terrasse_rechts:
      friendly_name: "Terrasse (rechts)"
      icon: hass:arrow-split-horizontal
    sensor.blind_control_terrasse_links:
      friendly_name: "Terrasse (links)"
      icon: hass:arrow-split-horizontal
    sensor.blind_control_schlafzimmer:
      friendly_name: "Schlafzimmer"
      icon: hass:arrow-split-horizontal
