input_select:
  climate_mode_ankleide:
    name: "Thermostat: Modus (Ankleide)"
    options:
      - "auto"
      - "heat"
      - "off"
  climate_mode_arbeitszimmer:
    name: "Thermostat: Modus (Arbeitszimmer)"
    options:
      - "auto"
      - "heat"
      - "off"
  climate_mode_badezimmer:
    name: "Thermostat: Modus (Badezimmer)"
    options:
      - "auto"
      - "heat"
      - "off"
  climate_mode_duschbad:
    name: "Thermostat: Modus (Duschbad)"
    options:
      - "auto"
      - "heat"
      - "off"
  climate_mode_flur:
    name: "Thermostat: Modus (Flur)"
    options:
      - "auto"
      - "heat"
      - "off"
  climate_mode_kueche:
    name: "Thermostat: Modus (Küche)"
    options:
      - "auto"
      - "heat"
      - "off"
  climate_mode_nino:
    name: "Thermostat: Modus (Nino)"
    options:
      - "auto"
      - "heat"
      - "off"
  climate_mode_noah:
    name: "Thermostat: Modus (Noah)"
    options:
      - "auto"
      - "heat"
      - "off"
  climate_mode_schlafzimmer:
    name: "Thermostat: Modus (Schlafzimmer)"
    options:
      - "auto"
      - "heat"
      - "off"
  climate_mode_wohnzimmer:
    name: "Thermostat: Modus (Wohnzimmer)"
    options:
      - "auto"
      - "heat"
      - "off"

automation:
  - alias: Window open, climate off after a defined time (Arbeitszimmer)
    description: ""
    use_blueprint:
      path: local/window-open-climate-off.yaml
      input:
        window_entity: binary_sensor.window_sensor_arbeitszimmer_window_is_open
        input_select_entity: input_select.climate_mode_arbeitszimmer
        minimum_open_time: 15
        climate_target: climate.room_climate_arbeitszimmer
    id: b40c868f709cbfcc5da380f34203936dd0732644
  - alias: Window open, climate off after a defined time (Badezimmer)
    description: ""
    use_blueprint:
      path: local/window-open-climate-off.yaml
      input:
        window_entity: binary_sensor.window_sensor_badezimmer_window_is_open
        input_select_entity: input_select.climate_mode_badezimmer
        climate_target: climate.room_climate_badezimmer
        minimum_open_time: 15
    id: 492714c1f82a6dcd71941c76656c2e3c3538e4db
  - alias: Window open, climate off after a defined time (Duschbad)
    description: ""
    use_blueprint:
      path: local/window-open-climate-off.yaml
      input:
        window_entity: binary_sensor.window_sensor_duschbad_window_is_open
        input_select_entity: input_select.climate_mode_duschbad
        climate_target: climate.room_climate_duschbad
        minimum_open_time: 15
    id: c91027cb28c5238dd8caf16ba84b83aee40035e7
  - alias: Window open, climate off after a defined time (Küche)
    description: ""
    use_blueprint:
      path: local/window-open-climate-off.yaml
      input:
        window_entity: binary_sensor.window_sensor_kueche_any_window_is_open
        input_select_entity: input_select.climate_mode_kueche
        climate_target: climate.room_climate_kuche
        minimum_open_time: 15
    id: 63872a4a53e400637f0ad7dc48edfa4e57b0585b
  - alias: Window open, climate off after a defined time (Nino)
    description: ""
    use_blueprint:
      path: local/window-open-climate-off.yaml
      input:
        window_entity: binary_sensor.window_sensor_nino_any_window_is_open
        input_select_entity: input_select.climate_mode_nino
        climate_target: climate.room_climate_nino
        minimum_open_time: 15
    id: cacea7bc38358a431ff2e408ee564cf885adb192
  - alias: Window open, climate off after a defined time (Noah)
    description: ""
    use_blueprint:
      path: local/window-open-climate-off.yaml
      input:
        window_entity: binary_sensor.window_sensor_noah_any_window_is_open
        input_select_entity: input_select.climate_mode_noah
        climate_target: climate.room_climate_noah
        minimum_open_time: 15
    id: bae4f2da1163edd3f828840af77b4aa09d0946a7
  - alias: Window open, climate off after a defined time (Schlafzimmer)
    description: ""
    use_blueprint:
      path: local/window-open-climate-off.yaml
      input:
        window_entity: binary_sensor.window_sensor_schlafzimmer_window_is_open
        input_select_entity: input_select.climate_mode_schlafzimmer
        climate_target: climate.room_climate_schlafzimmer
        minimum_open_time: 15
    id: 703a5ed88ceb7a45de2a2a59ae4f13368f58b6b4
  - alias: Window open, climate off after a defined time (Wohnzimmer)
    description: ""
    use_blueprint:
      path: local/window-open-climate-off.yaml
      input:
        window_entity: binary_sensor.window_sensor_wohnzimmer_any_window_is_open
        input_select_entity: input_select.climate_mode_wohnzimmer
        climate_target: climate.room_climate_wohnzimmer
        minimum_open_time: 15
    id: 45eb374032361b6c0bd685a2800dbbb8f2cdc2a3
