velux:
  host: !secret velux-gateway-host
  password: !secret velux-gateway-password

automation:
  - alias: KLF reboot on Home Assistant shutdown
    description: Reboots the KLF200 in order to avoid SSL Handshake issue
    trigger:
      - platform: homeassistant
        event: shutdown
    action:
      - service: velux.reboot_gateway
    id: ebc073c2c786877704b0bc82e5c78fe94822d54e

input_boolean:
  auto_cooling_ankleide:
    name: "Kühlautomatik Lichtkuppel (Ankleide)"
    icon: mdi:snowflake
  auto_cooling_flur:
    name: "Kühlautomatik Lichtkuppel (Flur)"
    icon: mdi:snowflake
