automation:
  - alias: Velux KLF200 reboot on Home Assistant shutdown
    description: Reboot the KLF200 gateway in order to avoid SSL handshake issue
    triggers:
      - trigger: homeassistant
        event: shutdown
    actions:
      - action: button.press
        data: {}
        target:
          entity_id: button.klf_200_gateway_neu_starten
    id: ebc073c2c786877704b0bc82e5c78fe94822d54e

input_boolean:
  auto_cooling_ankleide:
    name: "Kühlautomatik Lichtkuppel (Ankleide)"
    icon: mdi:snowflake
  auto_cooling_flur:
    name: "Kühlautomatik Lichtkuppel (Flur)"
    icon: mdi:snowflake

template:
  - binary_sensor:
      - name: regensensor_lichtkuppel_flur_is_wet
        state: >
          {{ 0 < states("sensor.regensensor_lichtkuppel_flur_voltage_3") | float(0) < 2 }}
        availability: >
          {{ not is_state('sensor.regensensor_lichtkuppel_flur_voltage_3', 'unavailable') }}
        icon: >
          {{ is_state("regensensor_lichtkuppel_flur_is_wet", "on") | iif("mdi:weather-pouring", "mdi:circle-outline") }}
        unique_id: fbe43771ee234abbedd9bbc35ebc33bcbb8faca0
