velux:
  host: !secret velux-gateway-host
  password: !secret velux-gateway-password

cover:
  - platform: template
    covers:
      lichtkuppel_ankleide:
        device_class: window
        friendly_name: Lichtkuppel Ankleide
        availability_template: >
          {{ not (is_state('switch.lichtkuppel_ankleide_up', 'unknown') or is_state('switch.lichtkuppel_ankleide_down', 'unknown')) }}
        position_template: >
          {{ is_state('binary_sensor.window_sensor_lichtkuppel_ankleide_is_open', 'on') * 100 }}
        open_cover:
          - service: cover.stop_cover
            entity_id: cover.lichtkuppel_ankleide
          - service: switch.turn_on
            entity_id: switch.lichtkuppel_ankleide_up
        close_cover:
          - service: cover.stop_cover
            entity_id: cover.lichtkuppel_ankleide
          - service: switch.turn_on
            entity_id: switch.lichtkuppel_ankleide_down
        stop_cover:
          service: switch.turn_off
          entity_id:
            - switch.lichtkuppel_ankleide_up
            - switch.lichtkuppel_ankleide_down
      lichtkuppel_flur:
        device_class: window
        friendly_name: Lichtkuppel Flur
        availability_template: >
          {{ not (is_state('switch.lichtkuppel_flur_up', 'unknown') or is_state('switch.lichtkuppel_flur_down', 'unknown')) }}
        position_template: >
          {{ is_state('binary_sensor.window_sensor_lichtkuppel_flur_is_open', 'on') * 100 }}
        open_cover:
          - service: cover.stop_cover
            entity_id: cover.lichtkuppel_flur
          - service: switch.turn_on
            entity_id: switch.lichtkuppel_flur_up
        close_cover:
          - service: cover.stop_cover
            entity_id: cover.lichtkuppel_flur
          - service: switch.turn_on
            entity_id: switch.lichtkuppel_flur_down
        stop_cover:
          service: switch.turn_off
          entity_id:
            - switch.lichtkuppel_flur_up
            - switch.lichtkuppel_flur_down

automation:
  - alias: Turn off Lichtkuppel switches after startup
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: cover.stop_cover
        entity_id:
          - cover.lichtkuppel_ankleide
          - cover.lichtkuppel_flur
    id: 273efb2ab2a6225f5accb803d52f3441ad99e6b1
  - alias: Turn off Lichtkuppel switches after 45 s
    trigger:
      - platform: state
        entity_id:
          - switch.lichtkuppel_ankleide_up
          - switch.lichtkuppel_ankleide_down
          - switch.lichtkuppel_flur_up
          - switch.lichtkuppel_flur_down
        to: "on"
        for: "00:00:45"
    action:
      - service: switch.turn_off
        target:
          entity_id: >
            {{ trigger.entity_id }}
    id: 7c90b4caff834c3036d746a21b50807fe655b844

input_boolean:
  auto_cooling_ankleide:
    name: "Kühlautomatik Lichtkuppel (Ankleide)"
    icon: mdi:snowflake
  auto_cooling_flur:
    name: "Kühlautomatik Lichtkuppel (Flur)"
    icon: mdi:snowflake
