sensor:
  - name: powerfox_api
    platform: rest
    authentication: basic
    username: !secret powerfox-user
    password: !secret powerfox-password
    scan_interval: 60
    timeout: 30
    resource: "https://backend.powerfox.energy/api/2.0/my/main/current?unit=kwh"
    value_template: "OK"
    json_attributes:
      - "Watt"
      - "A_Plus"
      - "A_Plus_HT"
      - "A_Plus_NT"
      - "A_Minus"
      - "Timestamp"

template:
  - sensor:
      - name: powerfox_power
        state: >
          {{ state_attr('sensor.powerfox_api', 'Watt') }}
        unit_of_measurement: W
        device_class: power
        state_class: measurement
        unique_id: 2eb011eac11aedc210863d36ba3829d2e6abd354
  - sensor:
      - name: powerfox_energy_bought
        state: >
          {{ state_attr('sensor.powerfox_api', 'A_Plus') }}
        unit_of_measurement: kWh
        device_class: energy
        state_class: total_increasing
        unique_id: 71bb34a59ea603b30ebe5d87985d9e6e99311f55
  - sensor:
      - name: powerfox_energy_sold
        state: >
          {{ state_attr('sensor.powerfox_api', 'A_Minus') }}
        unit_of_measurement: kWh
        device_class: energy
        state_class: total_increasing
        unique_id: fbf46ab7931f0936dc0dd6f436c8a20b683a9368
