automation:
  - alias: Export power meter to Google Sheets
    triggers:
      trigger: time_pattern
      minutes: "/15"
    conditions:
      condition: numeric_state
      entity_id: sensor.last_meter_consumption_zuhause
      above: 0
    actions:
      - action: google_sheets.append_sheet
        data:
          config_entry: d4c1ba49aae5a528a9d94645412bfb32
          worksheet: "Power Meter"
          data:
            time: "{{ utcnow() | as_timestamp | round }}"
            consumption: "{{ states('sensor.last_meter_consumption_zuhause') | float(0) }}"
            electricity_price: 0.2912
            production: "{{ states('sensor.solartisch_yieldtotal') | float(0) }}"
    id: d698e01895aab3aead886032a61e945c169dd5b6
  - alias: Tibber Reload
    triggers:
      trigger: state
      entity_id: sensor.last_meter_consumption_zuhause
      for:
        hours: 0
        minutes: 5
        seconds: 0
    actions:
      - action: homeassistant.reload_config_entry
        data:
          entry_id: 25ee964f751e61a9c053d2e5932b56a8
    mode: single
    id: e9d1b7990a76e7c8a9af0b400e0b9e435f0a5ca5

sensor:
  - platform: filter
    name: energy_average_power
    entity_id: sensor.average_power_zuhause
    filters:
      - filter: time_throttle
        window_size: "00:01:00"
    unique_id: 6057afc61360324ed0e5d471617630c277e8502b
  - platform: filter
    name: energy_last_meter_consumption
    entity_id: sensor.last_meter_consumption_zuhause
    filters:
      - filter: time_throttle
        window_size: "00:01:00"
        precision: 3
    unique_id: 25996c3b9d7ec9ba80da412ba82a4c615eb2bc7b
  - platform: filter
    name: energy_power
    entity_id: sensor.power_zuhause
    filters:
      - filter: time_throttle
        window_size: "00:01:00"
        precision: 0
    unique_id: f0caf5aa2f3073a85ecf6498d100ea9135d8ed40
