bhyve:
  username: !secret bhyve_username
  password: !secret bhyve_password

sensor:
  - platform: bhyve

switch:
  - platform: bhyve

binary_sensor:
  - platform: bhyve

input_button:
  watering_start:
    name: "Bewässerung: Start"
    icon: mdi:watering-can

input_datetime:
  watering_time:
    name: "Bewässerung: Dauer"
    has_time: true
    icon: mdi:timer

automation:
  - alias: "Bewässerung: Start"
    trigger:
      - platform: state
        entity_id: input_button.watering_start
    action:
      - service: bhyve.start_watering
        data:
          entity_id: switch.terrasse_zone
          minutes: >
            {{ state_attr('input_datetime.watering_time', 'timestamp') // 60 }}
    id: 038ab65ebeeb5c748074a352e57b8245a811d08f
  - alias: "B-Hyve: Update next watering start & rain delay finish"
    trigger:
      - platform: state
        entity_id: switch.terrasse_zone, switch.ventil_1_rain_delay
      - platform: homeassistant
        event: start
    action:
      - service: python_script.bhyve_next_watering
        data:
          entity_id: switch.bhyve_zone_terrasse
    id: e2d9e7a9dc013525354d149ec61cf27787df102f
