homematic:
  interfaces:
    rf:
      host: !secret homematic-host
      username: !secret homematic-user
      password: !secret homematic-password
      port: 2001
      resolvenames: json
    ip:
      host: !secret homematic-host
      username: !secret homematic-user
      password: !secret homematic-password
      port: 2010
      resolvenames: json
    groups:
      host: !secret homematic-host
      username: !secret homematic-user
      password: !secret homematic-password
      port: 9292
      resolvenames: json
      path: /groups
  hosts:
    central:
      host: !secret homematic-host
      username: !secret homematic-user
      password: !secret homematic-password

timer:
  homematic_watchdog_timeout:
    name: "Homematic Watchdog: Timeout"
    duration: "00:10:00"

sensor:
  - platform: template
    sensors:
      homematic_last_reboot:
        friendly_name: "letzter Neustart (Homematic)"
        value_template: "{{ strptime(state_attr('homematic.central', 'last_reboot') or '1970-01-01 00:00:00', '%Y-%m-%d %H:%M:%S').isoformat() }}"
        device_class: "timestamp"
        icon_template: "mdi:clock"

automation:
  - alias: "Homematic Watchdog"
    trigger:
      - platform: homeassistant
        event: start
      - platform: event # Homematic keepalive at periods < timer.homematic_watchdog_timeout.duration
        event_type: homematic.keypress
        event_data:
          name: HM-RCV-50 BidCoS-RF
          channel: 1
          param: PRESS_SHORT
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.homematic_watchdog_timeout
    action:
      - service: timer.start
        entity_id: timer.homematic_watchdog_timeout
      - condition: and
        conditions: "{{ trigger.event.event_type == 'timer.finished' }}"
      - service: homematic.reconnect
      - service: notify.telegram_admin
        data:
          message: "Homematic dead. Attempting to reconnect ..."

  - alias: Update OpenWeatherMap on Homematic
    trigger:
      platform: state
      entity_id: sensor.openweathermap_last_updated
    action:
      - service: homematic.set_variable_value
        target:
          entity_id: homematic.central
        data:
          name: "openweathermap_cloud_coverage"
          value: "{{ states('sensor.openweathermap_cloud_coverage') | float }}"
      - service: homematic.set_variable_value
        target:
          entity_id: homematic.central
        data:
          name: "openweathermap_humidity"
          value: "{{ states('sensor.openweathermap_humidity') | float }}"
      - service: homematic.set_variable_value
        target:
          entity_id: homematic.central
        data:
          name: "openweathermap_pressure"
          value: "{{ states('sensor.openweathermap_pressure') | float }}"
      - service: homematic.set_variable_value
        target:
          entity_id: homematic.central
        data:
          name: "openweathermap_rain"
          value: "{{ states('sensor.openweathermap_rain') | float }}"
      - service: homematic.set_variable_value
        target:
          entity_id: homematic.central
        data:
          name: "openweathermap_temperature"
          value: "{{ states('sensor.openweathermap_temperature') | float }}"
      - service: homematic.set_variable_value
        target:
          entity_id: homematic.central
        data:
          name: "openweathermap_wind_bearing"
          value: "{{ states('sensor.openweathermap_wind_bearing') | float }}"
      - service: homematic.set_variable_value
        target:
          entity_id: homematic.central
        data:
          name: "openweathermap_wind_speed"
          value: "{{ states('sensor.openweathermap_wind_speed') | float }}"
