light:
  - platform: group
    name: Arbeitszimmer
    entities:
      - light.color_temperature_light_1
  - platform: group
    name: Küche
    entities:
      - light.color_temperature_light_1_2
  - platform: group
    name: Nino
    entities:
      - light.hue_color_lamp_1_2
      - light.hue_color_lamp_2_2
      - light.hue_color_lamp_3_2
  - platform: group
    name: Noah
    entities:
      - light.hue_color_lamp_1
      - light.hue_color_lamp_2
      - light.hue_color_lamp_3
  - platform: group
    name: Schlafzimmer
    entities:
      - light.hue_ambiance_lamp_1
      - light.hue_ambiance_lamp_2
      - light.hue_ambiance_lamp_3
  - platform: group
    name: Wohnzimmer
    entities:
      - light.hue_color_floor_1
      - light.hue_go_1
      - light.hue_lightstrip_plus_1
      - light.hue_color_lamp_1_3
      - light.hue_color_lamp_1_4
automation:
  - alias: Turn off light at night (Terrasse)
    trigger:
      - platform: time
        at: "00:00:00"
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.licht_terrasse
    id: 5d15ac34081241e5a8bd709424da664f
  - alias: Motion-activated Switch (Küche)
    description: ""
    use_blueprint:
      path: local/motion_switch.yaml
      input:
        motion_entity: binary_sensor.motion_sensor_kueche_home_security_motion_detection
        illuminance_entity: sensor.motion_sensor_kueche_illuminance
        max_illuminance: 300
        no_motion_wait: 170 # total: 180 seconds
        switch_target:
          entity_id: switch.steckdose_kueche_oberschrank
    id: "1631694664177"
  - alias: Motion-activated Switch (Ankleide)
    description: ""
    use_blueprint:
      path: local/motion_switch.yaml
      input:
        motion_entity: binary_sensor.hue_motion_sensor_1_motion
        illuminance_entity: sensor.hue_motion_sensor_1_illuminance
        max_illuminance: 100
        no_motion_wait: 30 # total: 60 seconds
        switch_target:
          entity_id: switch.licht_ankleide
    id: "1631993327255"
  - alias: Christmas lights (turn on)
    trigger:
      - platform: time
        at: "06:00:00"
      - platform: sun
        event: sunset
        offset: "-00:30:00"
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.popp_smart_outdoor_plug_ip44_rated
  - alias: Christmas lights (turn off)
    trigger:
      - platform: sun
        event: sunrise
        offset: "00:30:00"
      - platform: time
        at: "23:00:00"
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.popp_smart_outdoor_plug_ip44_rated

homeassistant:
  customize:
    binary_sensor.0x001788010329dfc5_occupancy:
      friendly_name: Bewegungssensor Ankleide
