light:
  - platform: switch
    name: wohnzimmer_artemide
    entity_id: switch.wohnzimmer_artemide
  - platform: switch
    name: wohnzimmer_esstisch
    entity_id: switch.licht_wohnzimmer_esstisch

automation:
  - alias: Turn off light at night (Terrasse)
    triggers:
      - trigger: time
        at: "00:00:00"
    actions:
      - action: switch.turn_off
        target:
          entity_id: switch.licht_terrasse
    id: 986d8fc3ada8f9a3189839d2a6129d61b86ffafb
  - alias: Motion-activated switch (Ankleide)
    description: ""
    use_blueprint:
      path: local/motion_switch.yaml
      input:
        motion_entity: binary_sensor.ankleide_motion_sensor_occupancy
        illuminance_entity: sensor.ankleide_motion_sensor_illuminance
        max_illuminance: 50
        no_motion_wait: 30 # total: 60 seconds
        switch_entity: switch.licht_ankleide
    id: de06c94d9f653c5bec9a63f691f695d00be55ceb
  - alias: Motion-activated switch (Abstellkammer)
    description: ""
    use_blueprint:
      path: local/motion_switch.yaml
      input:
        motion_entity: binary_sensor.bewegungssensor_abstellkammer_motion_detection
        illuminance_entity: sensor.bewegungssensor_abstellkammer_illuminance
        max_illuminance: 50
        no_motion_wait: 30 # total: 60 seconds
        switch_entity: switch.licht_abstellkammer
    id: 17d77010fb15ef2b31b998f84061ba712feae824
  - alias: Motion-activated switch (Abstellkammer Terrasse)
    description: ""
    use_blueprint:
      path: local/motion_switch.yaml
      input:
        motion_entity: binary_sensor.bewegungssensor_abstellkammer_terrasse_motion_detection
        illuminance_entity: sensor.bewegungssensor_abstellkammer_terrasse_illuminance
        max_illuminance: 50
        no_motion_wait: 30 # total: 60 seconds
        switch_entity: switch.licht_abstellkammer_terrasse
    id: 5515115774a657a7926c70b2f2d5bbc6e1fc65e4
  - alias: Motion-activated light (Flur)
    description: ""
    use_blueprint:
      path: local/motion_light.yaml
      input:
        motion_entity: binary_sensor.flur_motion_sensor_occupancy
        illuminance_entity: sensor.flur_motion_sensor_illuminance
        max_illuminance: 15
        no_motion_wait: 30 # total: 120 seconds
        light_entity: light.flur
    id: 817e663b16db1110ce2068724e81619124e96c14
  - alias: Motion-activated switch (Küche)
    description: ""
    use_blueprint:
      path: local/motion_switch.yaml
      input:
        motion_entity: binary_sensor.bewegungssensor_kuche_motion_detection
        illuminance_entity: sensor.bewegungssensor_kuche_illuminance
        max_illuminance: 100
        no_motion_wait: 60 # total: 300 seconds
        switch_entity: switch.steckdose_kueche_oberschrank
    id: 1172df0cb260b2ec865568f441cd7c5777916a3e
#  - alias: Christmas lights (turn on)
#    triggers:
#      - trigger: time
#        at: "06:00:00"
#      - trigger: sun
#        event: sunset
#        offset: "-00:30:00"
#    actions:
#      - action: switch.turn_on
#        target:
#          entity_id: switch.popp_smart_outdoor_plug_ip44_rated
#    id: 9a72ce70359b6e1d631acc5ef42694d338945960
#  - alias: Christmas lights (turn off)
#    triggers:
#      - trigger: sun
#        event: sunrise
#        offset: "00:30:00"
#      - trigger: time
#        at: "23:00:00"
#    actions:
#      - action: switch.turn_off
#        target:
#          entity_id: switch.popp_smart_outdoor_plug_ip44_rated
#    id: e6be6b315bde7594302aba720ef4fcf86f54870a

homeassistant:
  customize:
    binary_sensor.0x001788010329dfc5_occupancy:
      friendly_name: Bewegungssensor Ankleide
