light:
  - platform: group
    name: Arbeitszimmer
    entities:
      - light.arbeitszimmer_deckenleuchte
  - platform: group
    name: Küche
    entities:
      - light.kueche_deckenleuchte
  - platform: group
    name: Nino
    entities:
      - light.hue_color_lamp_1_2
      - light.hue_color_lamp_2_2
      - light.hue_color_lamp_3_2
  - platform: group
    name: Noah
    entities:
      - light.hue_color_lamp_1
      - light.hue_color_lamp_2
      - light.hue_color_lamp_3
  - platform: group
    name: Schlafzimmer
    entities:
      - light.schlafzimmer_1
      - light.schlafzimmer_2
      - light.schlafzimmer_3
  - platform: group
    name: Wohnzimmer
    entities:
      - light.hue_color_floor_1
      - light.hue_go_1
      - light.hue_lightstrip_plus_1
      - light.hue_color_lamp_1_3
      - light.hue_color_lamp_1_4
automation:
  - alias: Turn off light at night (Terrasse)
    trigger:
      - platform: time
        at: "00:00:00"
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.licht_terrasse
    id: 986d8fc3ada8f9a3189839d2a6129d61b86ffafb
  - alias: Motion-activated switch (Küche)
    description: ""
    use_blueprint:
      path: local/motion_switch.yaml
      input:
        motion_entity: binary_sensor.motion_sensor_kueche_home_security_motion_detection
        illuminance_entity: sensor.motion_sensor_kueche_illuminance
        max_illuminance: 300
        no_motion_wait: 60 # total: 180 seconds
        switch_target:
          entity_id: switch.steckdose_kueche_oberschrank
    id: 1172df0cb260b2ec865568f441cd7c5777916a3e
  - alias: Motion-activated switch (Ankleide)
    description: ""
    use_blueprint:
      path: local/motion_switch.yaml
      input:
        motion_entity: binary_sensor.ankleide_motion_sensor_occupancy
        illuminance_entity: sensor.ankleide_motion_sensor_illuminance_lux
        max_illuminance: 100
        no_motion_wait: 30 # total: 60 seconds
        switch_target:
          entity_id: switch.licht_ankleide
    id: de06c94d9f653c5bec9a63f691f695d00be55ceb
  - alias: Motion-activated switch (Abstellkammer)
    description: ""
    use_blueprint:
      path: local/motion_switch.yaml
      input:
        motion_entity: binary_sensor.bewegungssensor_abstellkammer_home_security_motion_detection
        illuminance_entity: sensor.bewegungssensor_abstellkammer_illuminance
        max_illuminance: 100
        no_motion_wait: 30 # total: 60 seconds
        switch_target:
          entity_id: switch.licht_abstellkammer
    id: 17d77010fb15ef2b31b998f84061ba712feae824
  - alias: Motion-activated switch (Abstellkammer Terrasse)
    description: ""
    use_blueprint:
      path: local/motion_switch.yaml
      input:
        motion_entity: binary_sensor.bewegungssensor_abstellkammer_terrasse_home_security_motion_detection
        illuminance_entity: sensor.bewegungssensor_abstellkammer_terrasse_illuminance
        max_illuminance: 100
        no_motion_wait: 30 # total: 60 seconds
        switch_target:
          entity_id: switch.licht_abstellkammer_terrasse
    id: 5515115774a657a7926c70b2f2d5bbc6e1fc65e4
  - alias: Christmas lights (turn on)
    trigger:
      - platform: time
        at: "06:00:00"
      - platform: sun
        event: sunset
        offset: "-00:30:00"
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.popp_smart_outdoor_plug_ip44_rated
    id: 9a72ce70359b6e1d631acc5ef42694d338945960
  - alias: Christmas lights (turn off)
    trigger:
      - platform: sun
        event: sunrise
        offset: "00:30:00"
      - platform: time
        at: "23:00:00"
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.popp_smart_outdoor_plug_ip44_rated
    id: e6be6b315bde7594302aba720ef4fcf86f54870a

homeassistant:
  customize:
    binary_sensor.0x001788010329dfc5_occupancy:
      friendly_name: Bewegungssensor Ankleide
