automation:
  - alias: Music in Living Room
    trigger:
      - platform: state
        entity_id: media_player.wohnzimmer
        to: "playing"
    condition:
      condition: state
      entity_id: switch.wohnzimmer_musik
      state: "off"
    action:
      - service: media_player.media_pause
        entity_id: media_player.wohnzimmer
      - service: switch.turn_on
        entity_id: switch.wohnzimmer_musik
      - service: media_player.media_play
        entity_id: media_player.wohnzimmer
    id: f192120ea02a4daf63a729928ec88ced48a60df8
