automation:
  - alias: Turn on Multimedia Devices
    triggers:
      - trigger: state
        entity_id: remote.wohnzimmer
        to: "on"
    conditions:
      not:
        condition: state
        entity_id: select.wohnzimmer_activities
        state: "Musik"
    actions:
      - action: switch.turn_on
        entity_id: switch.steckdose_wohnzimmer_tv_switch
    id: ca1a524508a89623988e7d6ffb9d4d1c300ac74b
  - alias: Turn off Multimedia Devices
    triggers:
      - trigger: state
        entity_id: remote.wohnzimmer
        to: "off"
        for:
          minutes: 5
    actions:
      - action: switch.turn_off
        entity_id: switch.steckdose_wohnzimmer_tv_switch
    id: c50a48a805c4ae5ed4dd46cff6d5ccabf6511bea
