input_button:
  node_red_restart:
    name: "starte Node-RED neu"
    icon: mdi:reload

automation:
  - alias: Restart Node-RED
    triggers:
      - trigger: state
        entity_id: input_button.node_red_restart
    actions:
      - action: hassio.addon_restart
        data:
          addon: a0d7b954_nodered
    id: 7b4f14d00e65981ce0b4264d23aa53c434d8dafb
  - alias: Restart Node-RED on (re)start of Home Assistant (with a delay)
    triggers:
      - trigger: homeassistant
        event: start
    actions:
      - delay:
          seconds: 15
      - action: input_button.press
        target:
          entity_id: input_button.node_red_restart
    id: 25f9cad10e37086bbcb78a5c79e26ea0a2861383
