sensor:
  - platform: rest
    name: regenradar
    scan_interval: 300
    json_attributes:
      - minutestorain
      - rainin30min
      - rainin60min
      - rainin120min
      - rainnow
      - raintext
    resource: https://morgenwirdes.de/api/v3/rain.php?lat=50.00143080658686&long=8.29971776989226
    value_template: "{{ value_json.raintext }}"

template:
  - binary_sensor:
      - name: regenradar_rainin30min
        state: >
          {{ state_attr('sensor.regenradar', 'rainin30min') | bool(false) }}
        icon: >
          {% if is_state("binary_sensor.regenradar_rainin30min", "on") %}
            mdi:weather-pouring
          {% else %}
            mdi:circle-outline
          {% endif %}
      - name: regenradar_rainin60min
        state: >
          {{ state_attr('sensor.regenradar', 'rainin60min') | bool(false) }}
        icon: >
          {% if is_state("binary_sensor.regenradar_rainin60min", "on") %}
            mdi:weather-pouring
          {% else %}
            mdi:circle-outline
          {% endif %}
      - name: regenradar_rainin120min
        state: >
          {{ state_attr('sensor.regenradar', 'rainin120min') | bool(false) }}
        icon: >
          {% if is_state("binary_sensor.regenradar_rainin120min", "on") %}
            mdi:weather-pouring
          {% else %}
            mdi:circle-outline
          {% endif %}
      - name: regenradar_rainnow
        state: >
          {{ state_attr('sensor.regenradar', 'rainnow') | bool(false) }}
        icon: >
          {% if is_state("binary_sensor.regenradar_rainnow", "on") %}
            mdi:weather-pouring
          {% else %}
            mdi:circle-outline
          {% endif %}
  - sensor:
      - name: regenradar_minutestorain
        state_class: measurement
        state: >
          {{ state_attr('sensor.regenradar', 'minutestorain') | int(0) }}
        unit_of_measurement: "min"

homeassistant:
  customize:
    binary_sensor.regenradar_rainin30min:
      friendly_name: "Regenradar: Regen in nächsten 30 Minuten"
    binary_sensor.regenradar_rainin60min:
      friendly_name: "Regenradar: Regen in nächsten 60 Minuten"
    binary_sensor.regenradar_rainin120min:
      friendly_name: "Regenradar: Regen in nächsten 120 Minuten"
    binary_sensor.regenradar_rainnow:
      friendly_name: "Regenradar: Regen jetzt"
    sensor.regenradar:
      friendly_name: "Regenradar"
    sensor.regenradar_minutestorain:
      friendly_name: "Regenradar: Regen für … Minuten"
