template:
  binary_sensor:
    - name: cert_expiry_close
      state: >
        {{ states('sensor.cert_expiry_days_left') | int(0) <= 7 }}
      icon: mdi:clock-alert-outline
  sensor:
    - name: cert_expiry_days_left
      state: >
        {{ (as_timestamp(states('sensor.cert_expiry_timestamp_nikipore_duckdns_org'), 0) - as_timestamp(now())) // (24 * 3600) }}
      unit_of_measurement: "days"
      icon: mdi:clock-end

automation:
  - alias: Restart certificate expiry integration on (re)start of Home Assistant (with a delay)
    trigger:
      - platform: homeassistant
        event: start
    action:
      - delay:
          seconds: 15
      - service: homeassistant.reload_config_entry
        data:
          entry_id: 26f0e15c2014316842e166fc7592ec11
    id: f768b468519b5e9c43e40b3d4dbbfb28ffa6aae7

homeassistant:
  customize:
    binary_sensor.cert_expiry_close:
      friendly_name: "Zertifikat läuft bald ab"
    sensor.cert_expiry_days_left:
      friendly_name: "Zertifikat gültig für"
