homeassistant:
  customize:
    sensor.0x00158d000412f308_temperature:
      friendly_name: Temperatur Wohnzimmer
    sensor.0x00158d000412f308_humidity:
      friendly_name: rel. Luftfeuchtigkeit Wohnzimmer
    sensor.0x00158d000412f308_pressure:
      friendly_name: Luftdruck Wohnzimmer
    sensor.0x00158d00041da63b_temperature:
      friendly_name: Temperatur Badezimmer
    sensor.0x00158d00041da63b_humidity:
      friendly_name: rel. Luftfeuchtigkeit Badezimmer
    sensor.0x00158d00041da63b_pressure:
      friendly_name: Luftdruck Badezimmer
    binary_sensor.0x001788010329dfc5_occupancy:
      friendly_name: Bewegungssensor Küche
    binary_sensor.door_window_sensor_7_access_control_window_door_is_open_5:
      friendly_name: Fenster Badezimmer
      device_class: window