template:
  binary_sensor:
    - name: window_sensor_wohnzimmer_any_window_is_open
      state: >
        {{ is_state("binary_sensor.window_sensor_wohnzimmer_window_is_open", "on") or is_state("binary_sensor.door_sensor_terrasse_access_control_door_is_open", "on") }}
    - name: window_sensor_kueche_any_window_is_open
      state: >
        {{ is_state("binary_sensor.window_sensor_kueche_links_window_is_open", "on") or is_state("binary_sensor.window_sensor_kueche_rechts_window_is_open", "on") }}
    - name: window_sensor_nino_any_window_is_open
      state: >
        {{ is_state("binary_sensor.window_sensor_nino_links_window_is_open", "on") or is_state("binary_sensor.window_sensor_nino_rechts_window_is_open", "on") }}
    - name: window_sensor_noah_any_window_is_open
      state: >
        {{ is_state("binary_sensor.window_sensor_noah_links_window_is_open", "on") or is_state("binary_sensor.window_sensor_noah_rechts_window_is_open", "on") }}

homeassistant:
  customize:
    sensor.0x00158d000412f308_temperature:
      friendly_name: Temperatur Wohnzimmer
    sensor.0x00158d000412f308_humidity:
      friendly_name: rel. Luftfeuchtigkeit Wohnzimmer
    sensor.0x00158d000412f308_pressure:
      friendly_name: Luftdruck Wohnzimmer
    sensor.0x00158d00041da63b_temperature:
      friendly_name: Temperatur Badezimmer
    sensor.0x00158d00041da63b_humidity:
      friendly_name: rel. Luftfeuchtigkeit Badezimmer
    sensor.0x00158d00041da63b_pressure:
      friendly_name: Luftdruck Badezimmer
    binary_sensor.0x001788010329dfc5_occupancy:
      friendly_name: Bewegungssensor Ankleide
    binary_sensor.window_sensor_badezimmer_window_is_open:
      friendly_name: Fenster Badezimmer
      device_class: window
    binary_sensor.window_sensor_arbeitszimmer_window_is_open:
      friendly_name: Fenster Arbeitszimmer
      device_class: window
    binary_sensor.window_sensor_duschbad_window_is_open:
      friendly_name: Fenster Duschbad
      device_class: window
    binary_sensor.window_sensor_schlafzimmer_window_is_open:
      friendly_name: Fenster Schlafzimmer
      device_class: window
    binary_sensor.window_sensor_wohnzimmer_any_window_is_open:
      friendly_name: Fenster Wohnzimmer (mindestens eins offen)
      device_class: window
    binary_sensor.window_sensor_kueche_any_window_is_open:
      friendly_name: Fenster Küche (mindestens eins offen)
      device_class: window
    binary_sensor.window_sensor_nino_any_window_is_open:
      friendly_name: Fenster Nino (mindestens eins offen)
      device_class: window
    binary_sensor.window_sensor_noah_any_window_is_open:
      friendly_name: Fenster Noah (mindestens eins offen)
      device_class: window
