homeassistant:
  customize:
    sensor.0x00158d000412f308_temperature:
      friendly_name: Temperatur
    sensor.0x00158d000412f308_humidity:
      friendly_name: rel. Luftfeuchtigkeit
    sensor.0x00158d000412f308_pressure:
      friendly_name: Luftdruck
    sensor.0x00158d00041da63b_temperature:
      friendly_name: Temperatur
    sensor.0x00158d00041da63b_humidity:
      friendly_name: rel. Luftfeuchtigkeit
    sensor.0x00158d00041da63b_pressure:
      friendly_name: Luftdruck
