automation:
  - alias: Toggle switch Arbeitszimmer Technik/Schreibtisch
    trigger:
      - platform: state
        entity_id: sensor.arbeitszimmer_knopf_schreibtisch_action
        to: single
    action:
      - service: switch.toggle
        target:
          entity_id: switch.steckdose_arbeitszimmer_switch
    id: f55998fe58dafe49fc3f9b2e99409c90714fa889
  - alias: Toggle Schlafzimmer Wi-Fi AP
    trigger:
      - platform: state
        entity_id: sensor.schlafzimmer_knopf_wifi_action
        to: single
    action:
      - service: switch.toggle
        target:
          entity_id: switch.switch_flur_ap_schlafzimmer_poe
    id: a737155d8fa6fc7d120c316ad7ab3236081a8e22
  - alias: Toggle switch Küche Oberschrank
    trigger:
      - platform: state
        entity_id: sensor.kueche_knopf_oberschrank_action
        to: single
    action:
      - service: switch.toggle
        target:
          entity_id: switch.steckdose_kueche_oberschrank
    id: 02705d1cdb128d9d2df45542e218291b3006b007
  - alias: Toggle motion detector Küche
    trigger:
      - platform: state
        entity_id: sensor.kueche_knopf_oberschrank_action
        to: double
    action:
    - service: automation.toggle
      data: {}
      target:
        entity_id: automation.motion_activated_switch_kueche
    id: 02705d1cdb128d9d2df45542e218291b3006b007

input_boolean:
  switch_auto_off_active_arbeitszimmer:
    name: "automatisch ausschalten (Arbeitszimmer)"
    icon: mdi:timer-stop-outline
  switch_auto_off_active_garage:
    name: "automatisch ausschalten (Garage)"
    icon: mdi:timer-stop-outline

input_number:
  switch_auto_off_timeout_arbeitszimmer:
    name: "automatisch ausschalten nach … Minuten (Arbeitszimmer)"
    icon: mdi:history
    min: 0
    max: 60
    step: 1
  switch_auto_off_timeout_garage:
    name: "automatisch ausschalten nach … Minuten (Garage)"
    icon: mdi:history
    min: 0
    max: 60
    step: 1
  switch_auto_off_threshold_arbeitszimmer:
    name: "automatisch ausschalten unter … W (Arbeitszimmer)"
    icon: mdi:current-ac
    min: 0
    max: 20
    step: 0.5
  switch_auto_off_threshold_garage:
    name: "automatisch ausschalten unter … W (Garage)"
    icon: mdi:current-ac
    min: 0
    max: 20
    step: 0.5
