automation:
  - alias: Toggle technology switch in Arbeitszimmer
    trigger:
      - platform: state
        entity_id: sensor.arbeitszimmer_schalter_wuerfel_side
    condition:
      - "{{ trigger.from_state.state not in ['unknown', 'unavailable'] }}"
      - "{{ trigger.to_state.state not in ['unknown', 'unavailable'] }}"
      - "{{ trigger.to_state.state != trigger.from_state.state }}"
    action:
      - service: switch.toggle
        target:
          entity_id: switch.steckdose_arbeitszimmer_switch
    id: f55998fe58dafe49fc3f9b2e99409c90714fa889
