automation:
  - alias: Toggle technology switch in Arbeitszimmer
    trigger:
      - platform: state
        entity_id: sensor.arbeitszimmer_schalter_wuerfel_side
    condition:
      - "{{ trigger.from_state.state not in ['unknown', 'unavailable'] }}"
      - "{{ trigger.to_state.state not in ['unknown', 'unavailable'] }}"
      - "{{ trigger.to_state.state != trigger.from_state.state }}"
    action:
      - service: switch.toggle
        target:
          entity_id: switch.steckdose_arbeitszimmer_switch
    id: f55998fe58dafe49fc3f9b2e99409c90714fa889

input_boolean:
  switch_auto_off_active_arbeitszimmer:
    name: "automatisch ausschalten (Arbeitszimmer)"
    icon: mdi:timer-stop-outline
  switch_auto_off_active_garage:
    name: "automatisch ausschalten (Garage)"
    icon: mdi:timer-stop-outline

input_number:
  switch_auto_off_timeout_arbeitszimmer:
    name: "automatisch ausschalten nach … Minuten (Arbeitszimmer)"
    icon: mdi:history
    min: 0
    max: 60
    step: 1
  switch_auto_off_timeout_garage:
    name: "automatisch ausschalten nach … Minuten (Garage)"
    icon: mdi:history
    min: 0
    max: 60
    step: 1
  switch_auto_off_threshold_arbeitszimmer:
    name: "automatisch ausschalten unter … W (Arbeitszimmer)"
    icon: mdi:current-ac
    min: 0
    max: 20
    step: 0.5
  switch_auto_off_threshold_garage:
    name: "automatisch ausschalten unter … W (Garage)"
    icon: mdi:current-ac
    min: 0
    max: 20
    step: 0.5

