automation:
  - alias: Toggle switch Arbeitszimmer Technik/Schreibtisch
    trigger:
      - platform: state
        entity_id: sensor.arbeitszimmer_knopf_schreibtisch_action
        to: single
    action:
      - service: switch.toggle
        target:
          entity_id: switch.steckdose_arbeitszimmer_switch
    id: f55998fe58dafe49fc3f9b2e99409c90714fa889
  - alias: Toggle switch Schlafzimmer Wi-Fi AP
    trigger:
      - platform: state
        entity_id: sensor.schlafzimmer_knopf_wifi_action
        to: single
    action:
      - service: switch.toggle
        target:
          entity_id: switch.switch_flur_ap_schlafzimmer_poe
    id: a737155d8fa6fc7d120c316ad7ab3236081a8e22
  - alias: Toggle switch Küche Oberschrank
    trigger:
      - platform: state
        entity_id: sensor.kueche_knopf_oberschrank_action
        to: single
    action:
      - service: switch.toggle
        target:
          entity_id: switch.steckdose_kueche_oberschrank
    id: 02705d1cdb128d9d2df45542e218291b3006b007
  - alias: Toggle automation Küche motion detector
    trigger:
      - platform: state
        entity_id: sensor.kueche_knopf_oberschrank_action
        to: double
    variables:
      automation: automation.motion_activated_switch_kuche_2
      mediaplayer: media_player.kuche
    action:
      - service: automation.toggle
        data: {}
        target:
          entity_id: "{{ automation }}"
      - service: notify.alexa_media
        data:
          message: >
            "Präsenzmelder ist {{ {"on": "angeschaltet", "off": "ausgeschaltet"}[states(automation)] }}"
          target: "{{ mediaplayer }}"
          data:
            type: announce
          title: >
            "Präsenzmelder ist {{ {"on": "angeschaltet", "off": "ausgeschaltet"}[states(automation)] }}"
    id: 6d75c7a1a7f3d6fef3e35cc5232085bceb1a653f

input_boolean:
  switch_auto_off_active_arbeitszimmer:
    name: "automatisch ausschalten (Arbeitszimmer)"
    icon: mdi:timer-stop-outline
  switch_auto_off_active_garage:
    name: "automatisch ausschalten (Garage)"
    icon: mdi:timer-stop-outline
  switch_auto_off_active_keller:
    name: "automatisch ausschalten (Keller)"
    icon: mdi:timer-stop-outline

input_number:
  switch_auto_off_timeout_arbeitszimmer:
    name: "automatisch ausschalten nach … Minuten (Arbeitszimmer)"
    icon: mdi:history
    min: 0
    max: 60
    step: 1
  switch_auto_off_timeout_garage:
    name: "automatisch ausschalten nach … Minuten (Garage)"
    icon: mdi:history
    min: 0
    max: 60
    step: 1
  switch_auto_off_timeout_keller:
    name: "automatisch ausschalten nach … Minuten (Keller)"
    icon: mdi:history
    min: 0
    max: 60
    step: 1
  switch_auto_off_threshold_arbeitszimmer:
    name: "automatisch ausschalten unter … W (Arbeitszimmer)"
    icon: mdi:current-ac
    min: 0
    max: 20
    step: 0.5
  switch_auto_off_threshold_garage:
    name: "automatisch ausschalten unter … W (Garage)"
    icon: mdi:current-ac
    min: 0
    max: 20
    step: 0.5
  switch_auto_off_threshold_keller:
    name: "automatisch ausschalten unter … W (Keller)"
    icon: mdi:current-ac
    min: 0
    max: 20
    step: 0.5
