input_select:
  washing_machine_status:
    name: "Waschmaschine: Status"
    options:
      - aus
      - arbeitet
      - fertig

sensor:
  - platform: average
    name: washing_machine_power
    entities:
      - sensor.steckdose_waschmaschine_current_consumption
    duration:
      seconds: 60
    precision: 1

homeassistant:
  customize:
    sensor.washing_machine_power:
      friendly_name: "Waschmaschine: Leistung"
