sensor:
  - platform: statistics
    name: weather_wind_speed_max_recent_statistics
    entity_id: sensor.weather_wind_speed
    state_characteristic: value_max
    sampling_size: 20
    max_age:
      minutes: 30

input_boolean:
  weather_raining:
    name: "Wetteralarm: Regen (überschreiben)"
    icon: mdi:weather-pouring
  weather_storm:
    name: "Wetteralarm: Sturm (überschreiben)"
    icon: mdi:weather-windy

template:
  - binary_sensor:
      - name: weather_raining
        state: >
          {{ is_state("input_boolean.weather_raining", "on") or not is_state('sensor.weather_precipitation', '0') }}
        icon: >
          {{ is_state("binary_sensor.weather_raining", "on") | iif("mdi:weather-pouring", "mdi:circle-outline") }}
        delay_off:
          minutes: 0
        unique_id: 434d5b21925833b3f83339753e335314f5b57ab7
      - name: weather_storm
        state: >
          {{ is_state("input_boolean.weather_storm", "on") or states('sensor.weather_forecast_wind_gusts') | float(0) >= 12.0 * 3.6 }}
        icon: >
          {{ is_state("binary_sensor.weather_storm", "on") | iif("mdi:weather-windy", "mdi:circle-outline") }}
        delay_off:
          minutes: 0
        unique_id: 72fcdde3459bab12c8411440631a0cace1ef57f8
  - sensor:
      - name: weather_forecast_cloud_coverage
        state_class: measurement
        unit_of_measurement: "%"
        state: >
          {{ states('sensor.openweathermap_hourly_forecast_cloud_coverage') }}
        icon: mdi:cloud-outline
        unique_id: ff64546a962af33f9963b99230b5933f0b8eb8b0
      - name: weather_forecast_dewpoint
        state_class: measurement
        unit_of_measurement: "°C"
        state: >
          {{ states('sensor.openweathermap_hourly_dew_point') }}
        device_class: temperature
        unique_id: aae66e017b8611dbd7ec2e079a92fca40742a628
      - name: weather_forecast_precipitation
        state_class: measurement
        unit_of_measurement: "mm"
        state: >
          {{ states('sensor.openweathermap_hourly_forecast_precipitation') }}
        icon: mdi:weather-rainy
        unique_id: 81bd5a634a62df3ec5b3add84d7b1bf09405c13a
      - name: weather_forecast_wind_gusts
        state_class: measurement
        unit_of_measurement: "km/h"
        state: >
          {{ states('sensor.wiesbaden_biebrich_windboen') }}
        icon: mdi:weather-windy
        unique_id: aeeb9fd8e90d71af4b489292711a1d5f0145fc0e
      - name: weather_forecast_sun_duration
        state_class: measurement
        unit_of_measurement: "s"
        state: >
          {{ states('sensor.wiesbaden_biebrich_sonnenscheindauer') }}
        icon: mdi:weather-sunny
        unique_id: 41acc499bee49362845013e9e570dccbd3be545f
      - name: weather_forecast_temperature
        state_class: measurement
        unit_of_measurement: "°C"
        state: >
          {{ states('sensor.openweathermap_hourly_temperature') }}
        device_class: temperature
        unique_id: bfc393bc63ce5dcced05d494b3334c75c32600e5
      - name: weather_forecast_temperature_high
        state_class: measurement
        unit_of_measurement: "°C"
        state: >
          {% set forecast = state_attr('sensor.weather_forecast_hourly', 'forecast') %}
          {% set i = max(0, (as_timestamp(state_attr('sun.sun', 'next_setting')) - as_timestamp(forecast[0]['datetime'])) // 3600) | int(0) %}
          {{ forecast[:i+2] | map(attribute='temperature') | max | float(0) }}
        device_class: temperature
        unique_id: 0be9418eb6a15776650c6f19366ef36ebf9355f6
      - name: weather_forecast_temperature_low
        state_class: measurement
        unit_of_measurement: "°C"
        state: >
          {% set forecast = state_attr('sensor.weather_forecast_hourly', 'forecast') %}
          {% set i = max(0, (as_timestamp(state_attr('sun.sun', 'next_rising')) - as_timestamp(forecast[0]['datetime'])) // 3600) | int(0) %}
          {{ forecast[:i+2] | map(attribute='temperature') | min | float(0) }}
        device_class: temperature
        unique_id: 140472b68120fb362cbbdb9b51f271520a94a8f8
      - name: weather_forecast_uv_index
        state_class: measurement
        unit_of_measurement: "UV index"
        state: >
          {{ states('sensor.openweathermap_hourly_uv_index') }}
        icon: mdi:sun-wireless-outline
        unique_id: 54ff35dd73f33792e5e57c15bf24dd266d2a6895
      - name: weather_humidity
        state_class: measurement
        unit_of_measurement: "%"
        state: >
          {{ states('sensor.openweathermap_hourly_humidity') }}
        device_class: humidity
        unique_id: 6d29af8fe42101df2d6268089b3d319b93fc9ac5
      - name: weather_precipitation
        state_class: measurement
        unit_of_measurement: "mm/h"
        state: >
          {{ states('sensor.openweathermap_hourly_rain') }}
        icon: mdi:weather-pouring
        unique_id: af3247a0fce76abbaa72abcf0c0461177a7ec35d
      - name: weather_pressure
        state_class: measurement
        unit_of_measurement: "mbar"
        state: >
          {{ states('sensor.openweathermap_hourly_pressure') }}
        device_class: pressure
        unique_id: 3acaaec5eb1c22a778cb498179fc3622bc59b8ce
      - name: weather_temperature
        state_class: measurement
        unit_of_measurement: "°C"
        state: >
          {{ states('sensor.openweathermap_hourly_temperature') }}
        device_class: temperature
        unique_id: 0201f803b8666e7c65b882e46f26f696e8b68fd6
      - name: weather_wind_direction
        state_class: measurement
        unit_of_measurement: "°"
        state: >
          {{ states('sensor.openweathermap_hourly_wind_bearing') }}
        icon: mdi:compass-outline
        unique_id: 14a308ee89a063c1de4ecf1d1f9a87296a7c4818
      - name: weather_wind_direction_text
        state: >
          {{ ['N','NNE','NE','ENE','E','ESE','SE','SSE','S','SSW','SW','WSW','W','WNW','NW','NNW'][((((states('sensor.weather_wind_direction') | float(0)) + 11.25) % 360) / 22.5) | int] }}
        icon: mdi:compass-outline
        unique_id: 07a3028300ec22d1051b95b0f05716f5b7cddde1
      - name: weather_wind_speed
        unit_of_measurement: "m/s"
        state_class: measurement
        state: >
          {{ states('sensor.windsensor_terrasse_velocity') }}
        icon: mdi:weather-windy
        unique_id: 4a25dd3a5352e5302e7e770f76028a447afe27b4
      - name: weather_wind_speed_max_recent
        unit_of_measurement: "m/s"
        state_class: "measurement"
        state: >
          {{ states('sensor.weather_wind_speed_max_recent_statistics') | float(states('sensor.weather_wind_speed')) }}
        icon: mdi:weather-windy
        unique_id: fc990b221a8260f2d8dc2b5c219c061ed72ddf54
      - name: weather_wind_force
        unit_of_measurement: "bft"
        state_class: measurement
        state: >
          {{ ([0, 0.3, 1.6, 3.4, 5.5, 8.0, 10.8, 13.9, 17.2, 20.8, 24.5, 28.5, 32.7] | select("<=", states('sensor.weather_wind_speed') | float(0)) | list | length) - 1 }}
        icon: mdi:weather-windy
        unique_id: e5ee24939fb385a1f4ddd366ab95194f0d78e6eb
  - trigger:
      - trigger: state
        entity_id: weather.openweathermap_hourly
      - trigger: time_pattern
        hours: /1
    action:
      - action: weather.get_forecasts
        data:
          type: hourly
        target:
          entity_id: weather.openweathermap_hourly
        response_variable: forecast
    sensor:
      - name: Weather Forecast Hourly
        unique_id: weather_forecast_hourly
        state: "{{ forecast['weather.openweathermap_hourly'].forecast[0].condition }}"
        availability: "{{ is_number(forecast['weather.openweathermap_hourly'].forecast[0].temperature) }}"
        attributes:
          forecast: "{{ forecast['weather.openweathermap_hourly'].forecast }}"

homeassistant:
  customize:
    binary_sensor.weather_raining:
      friendly_name: "Wetteralarm: Regen"
    binary_sensor.weather_raining_bayesian:
      friendly_name: "Wetteralarm: Regen (Bayesian)"
    binary_sensor.weather_storm:
      friendly_name: "Wetteralarm: Sturm"
    sensor.weather_forecast_cloud_coverage:
      friendly_name: "Wolkenbedeckung"
    sensor.weather_forecast_dewpoint:
      friendly_name: "Taupunkt"
    sensor.weather_forecast_precipitation:
      friendly_name: "Niederschlag"
    sensor.weather_forecast_wind_gusts:
      friendly_name: "Windböen"
    sensor.weather_forecast_sun_duration:
      friendly_name: "Sonnenscheindauer"
    sensor.weather_forecast_temperature_high:
      friendly_name: "Temperatur (max.)"
    sensor.weather_forecast_temperature_interpolated:
      friendly_name: "Temperatur (Vorhersage)"
    sensor.weather_forecast_temperature_low:
      friendly_name: "Temperatur (min.)"
    sensor.weather_humidity:
      friendly_name: "relative Luftfeuchtigkeit"
    sensor.weather_precipitation:
      friendly_name: "Niederschlag"
    sensor.weather_pressure:
      friendly_name: "Luftdruck"
    sensor.weather_temperature:
      friendly_name: "Temperatur"
    sensor.weather_wind_direction:
      friendly_name: "Windrichtung"
    sensor.weather_wind_direction_text:
      friendly_name: "Windrichtung (Kompass)"
    sensor.weather_wind_force:
      friendly_name: "Windstärke"
    sensor.weather_wind_speed:
      friendly_name: "Windgeschwindigkeit"
    sensor.weather_wind_speed_max_recent:
      friendly_name: "Windgeschwindigkeit (letzte Bö)"
