sensor:
  - platform: dwd_weather_warnings
    region_name: Stadt Frankfurt am Main
    name: Frankfurt am Main
  - platform: template
    sensors:
      weather_hourly_forecast_index:
        friendly_name: "Wettervorhersage: Index der aktuellen Stunde"
        value_template: "{{ (((utcnow() - state_attr('weather.dwd_weather_frankfurt_m_1h', 'forecast_time_utc')).total_seconds() // 3600) - 1) | max(0) | int }}"
      weather_forecast_time:
        friendly_name: "Wetter: Zeitpunkt der Vorhersage"
        value_template: "{{ state_attr('weather.dwd_weather_frankfurt_m_1h', 'forecast_time_utc') }}"
        device_class: timestamp
      weather_latest_update:
        friendly_name: "Wetter: zuletzt aktualisiert"
        value_template: "{{ state_attr('weather.dwd_weather_frankfurt_m_1h', 'latest_update_utc') }}"
        device_class: timestamp
      weather_forecast_cloud_coverage:
        friendly_name: "Wolkenbedeckung"
        unit_of_measurement: "%"
        value_template: "{{ state_attr('sensor.cloud_coverage_frankfurt_m_1h', 'data')[states('sensor.weather_hourly_forecast_index') | int]['value'] | float }}"
        icon_template: mdi:cloud-outline
      weather_forecast_dewpoint:
        friendly_name: "Taupunkt"
        unit_of_measurement: "°C"
        value_template: "{{ state_attr('sensor.dewpoint_frankfurt_m_1h', 'data')[states('sensor.weather_hourly_forecast_index') | int]['value'] | float }}"
        device_class: temperature
      weather_forecast_precipitation:
        friendly_name: "Niederschlag"
        unit_of_measurement: "mm"
        value_template: "{{ state_attr('sensor.precipitation_frankfurt_m_1h', 'data')[states('sensor.weather_hourly_forecast_index') | int]['value'] | float }}"
        icon_template: mdi:weather-rainy
      weather_forecast_wind_gusts:
        friendly_name: "Windböen"
        unit_of_measurement: "km/h"
        value_template: "{{ state_attr('sensor.wind_gusts_frankfurt_m_1h', 'data')[states('sensor.weather_hourly_forecast_index') | int]['value'] | float * 3.6 }}"
        icon_template: mdi:weather-rainy
      weather_humidity:
        friendly_name: "relative Luftfeuchtigkeit"
        unit_of_measurement: "%"
        value_template: "{{ state_attr('weather.dwd_weather_frankfurt_m_1h', 'humidity') | float }}"
        device_class: humidity
      weather_pressure:
        friendly_name: "Luftdruck"
        unit_of_measurement: "mbar"
        value_template: "{{ state_attr('weather.dwd_weather_frankfurt_m_1h', 'pressure') | float }}"
        device_class: pressure
      weather_temperature:
        friendly_name: "Temperatur"
        unit_of_measurement: "°C"
        value_template: "{{ state_attr('weather.dwd_weather_frankfurt_m_1h', 'temperature') | float }}"
        device_class: temperature
      weather_wind_bearing:
        friendly_name: "Windrichtung"
        unit_of_measurement: "°"
        value_template: "{{ state_attr('weather.dwd_weather_frankfurt_m_1h', 'wind_bearing') | float }}"
        icon_template: mdi:compass-outline
      weather_wind_speed:
        friendly_name: "Windgeschwindigkeit"
        unit_of_measurement: "km/h"
        value_template: "{{ state_attr('weather.dwd_weather_frankfurt_m_1h', 'wind_speed') | float }}"
        icon_template: mdi:weather-windy
