sensor:
  - platform: dwd_weather_warnings
    region_name: Stadt Frankfurt am Main
    name: Frankfurt am Main

template:
  binary_sensor:
    - name: weather_raining
      state: >
        {{ is_state("input_boolean.blind_control_raining", "on") }}
      icon: >
        {% if is_state("binary_sensor.weather_raining", "on") %}
          mdi:weather-pouring
        {% else %}
          mdi:circle-outline
        {% endif %}
    - name: weather_storm
      state: >
        {{ states('sensor.weather_wind_speed') | float > 6 }}
      icon: >
        {% if is_state("binary_sensor.weather_storm", "on") %}
          mdi:weather-windy
        {% else %}
          mdi:circle-outline
        {% endif %}
  sensor:
    - name: sun_azimuth
      unit_of_measurement: "°"
      state: >
        {{ state_attr('sun.sun', 'azimuth') }}
      icon: mdi:weather-sunny
    - name: sun_elevation
      unit_of_measurement: "°"
      state: >
        {{ state_attr('sun.sun', 'elevation') }}
      icon: mdi:weather-sunset-up
    - name: weather_hourly_forecast_index_next_rising
      state: >
        {{ ((as_timestamp(state_attr('sun.sun', 'next_rising')) - as_timestamp(state_attr('weather.dwd_weather_wiesbaden_biebrich_1h', 'forecast')[0]['datetime'])) // 3600) | max(0) }}
    - name: weather_hourly_forecast_index_next_setting
      state: >
        {{ ((as_timestamp(state_attr('sun.sun', 'next_setting')) - as_timestamp(state_attr('weather.dwd_weather_wiesbaden_biebrich_1h', 'forecast')[0]['datetime'])) // 3600) | max(0) }}
    - name: weather_latest_update
      state: >
        {{ state_attr('weather.dwd_weather_wiesbaden_biebrich_1h', 'latest_update_utc') }}
      device_class: timestamp
    - name: weather_forecast_cloud_coverage
      unit_of_measurement: "%"
      state: >
        {{ states('sensor.cloud_coverage_wiesbaden_biebrich_1h') | float }}
      icon: mdi:cloud-outline
    - name: weather_forecast_dewpoint
      unit_of_measurement: "°C"
      state: >
        {{ states('sensor.dewpoint_wiesbaden_biebrich_1h') | float }}
      device_class: temperature
    - name: weather_forecast_precipitation
      unit_of_measurement: "mm"
      state: >
        {{ states('sensor.precipitation_wiesbaden_biebrich_1h') | float }}
      icon: mdi:weather-rainy
    - name: weather_forecast_wind_gusts
      unit_of_measurement: "km/h"
      state: >
        {{ states('sensor.wind_gusts_wiesbaden_biebrich_1h') | float }}
      icon: mdi:weather-rainy
    - name: weather_forecast_sun_duration
      unit_of_measurement: "s"
      state: >
        {{ states('sensor.sensor.sun_duration_wiesbaden_biebrich_1h') | float }}
      icon: mdi:weather-sunny
    - name: weather_forecast_temperature_high
      unit_of_measurement: "°C"
      state: >
        {{ state_attr('sensor.temperature_wiesbaden_biebrich_1h', 'data')[:(states('sensor.weather_hourly_forecast_index_next_setting') | int) + 1] | map(attribute='value') | max | float }}
      device_class: temperature
    - name: weather_forecast_temperature_low
      unit_of_measurement: "°C"
      state: >
        {{ state_attr('sensor.temperature_wiesbaden_biebrich_1h', 'data')[:(states('sensor.weather_hourly_forecast_index_next_rising') | int) + 1] | map(attribute='value') | min | float }}
      device_class: temperature
    - name: weather_humidity
      unit_of_measurement: "%"
      state: >
        {{ state_attr('weather.dwd_weather_wiesbaden_biebrich_1h', 'humidity') | float }}
      device_class: humidity
    - name: weather_pressure
      unit_of_measurement: "mbar"
      state: >
        {{ state_attr('weather.dwd_weather_wiesbaden_biebrich_1h', 'pressure') | float }}
      device_class: pressure
    - name: weather_temperature
      unit_of_measurement: "°C"
      state: >
        {{ state_attr('weather.dwd_weather_wiesbaden_biebrich_1h', 'temperature') | float }}
      device_class: temperature
    - name: weather_wind_bearing
      unit_of_measurement: "°"
      state: >
        {{ state_attr('weather.dwd_weather_wiesbaden_biebrich_1h', 'wind_bearing') | float }}
      icon: mdi:compass-outline
    - name: weather_wind_speed
      unit_of_measurement: "m/s"
      state: >
        {{ (states('sensor.z_weather_velocity') | float) }}
      icon: mdi:weather-windy
    - name: weather_wind_force
      unit_of_measurement: "bft"
      state: >
        {{ ([0, 0.3, 1.6, 3.4, 5.5, 8.0, 10.8, 13.9, 17.2, 20.8, 24.5, 28.5, 32.7] | select("<=", states('sensor.weather_wind_speed') | float) | list | length) - 1 }}
      icon: mdi:weather-windy

homeassistant: 
  customize:
    sensor.sun_azimuth:
      friendly_name: "Sonnenstand (Azimut)"
    sensor.sun_elevation:
      friendly_name: "Sonnenstand (Höhe)"
    binary_sensor.weather_raining:
      friendly_name: "Wettersensor: Regen"
    binary_sensor.weather_storm:
      friendly_name: "Wettersensor: Sturm"
    sensor.weather_hourly_forecast_index_next_rising:
      friendly_name: "Wettervorhersage: Index des nächsten Sonnenaufgangs"
    sensor.weather_hourly_forecast_index_next_setting:
      friendly_name: "Wettervorhersage: Index des nächsten Sonnenuntergangs"
    sensor.weather_latest_update:
      friendly_name: "Wetter: zuletzt aktualisiert"
    sensor.weather_forecast_cloud_coverage:
      friendly_name: "Wolkenbedeckung"
    sensor.weather_forecast_dewpoint:
      friendly_name: "Taupunkt"
    sensor.weather_forecast_precipitation:
      friendly_name: "Niederschlag"
    sensor.weather_forecast_wind_gusts:
      friendly_name: "Windböen"
    sensor.weather_forecast_sun_duration:
      friendly_name: "Sonnenscheindauer"
    sensor.weather_forecast_temperature_high:
      friendly_name: "Temperatur (max.)"
    sensor.weather_forecast_temperature_low:
      friendly_name: "Temperatur (min.)"
    sensor.weather_humidity:
      friendly_name: "relative Luftfeuchtigkeit"
    sensor.weather_pressure:
      friendly_name: "Luftdruck"
    sensor.weather_temperature:
      friendly_name: "Temperatur"
    sensor.weather_wind_bearing:
      friendly_name: "Windrichtung"
    sensor.weather_wind_force:
      friendly_name: "Windstärke"
    sensor.weather_wind_speed:
      friendly_name: "Windgeschwindigkeit"
